### ISSUE TITLE
The lack of type initialization causes Jython crashing.

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#109]
In the following example,  OSError_new() does not initialize causing Jython crashing.

test.py
```
class C(ValueError, OSError):pass
C = OSError.__new__(C)
str(C)

```

Crash report:
> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py 
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     str(c)
> java.lang.ArrayIndexOutOfBoundsException: 0
> 	at org.python.core.PyBaseExceptionDerived.getSlot(PyBaseExceptionDerived.java:9)
> 	at org.python.core.PySlot.member_descriptor___get__(PySlot.java:37)
> 	at org.python.core.PySlot.__get__(PySlot.java:30)
> 	at org.python.core.PyObject.object___findattr__(PyObject.java:3706)
> 	at org.python.core.PyObject.object___getattribute__(PyObject.java:3690)
> 	......
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1275)
> 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
> 	at org.python.util.jython.run(jython.java:247)
> 	at org.python.util.jython.main(jython.java:129)
> 
> java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by Stewori** [comment]
@xiaxinmeng I noticed that you just opened a whole bunch of issues (selected this one randomly to reply). I appreciate that you undertake the effort to report these issues, however also noticed you are using Jython 2.5. The following applies to all issues you opened (assuming all occurred on the same platform):

Before you move on, be aware that Jython 2.5.3 is widely considered obsolete. In every issue you open for Jython < 2.7.2 you will soon be asked whether the issue is still present on current Jython. So I recommend you to re-evaluate all issues you just opened with current Jython, even better with current master if you can.
That said, note that most likely no work will be invested into Jython 2.5 any more (sure, it's open source and I can't speak for everyone. But I am rather confident I speak for all current core devs regarding this matter).
There will probably be a Jython 2.7.3 release with some bugfixes, which is again why your best bet is to report issues for Jython 2.7. However there is no promise that a 2.7.3 release will actually happen, because most work is now going into Jython 3 (but [that's another story](https://www.jython.org/jython-3-roadmap)).

**Comment by xiaxinmeng** [comment]
Thank you for your suggestion! I am going to try all my reported issues on the master (Jython 2.7.3a1-DEV). 

This one still causes NullPointerException on  the master. The crash report attached:

Crash report:

> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     str(C)
> java.lang.NullPointerException
> 	at org.python.core.exceptions.EnvironmentError__str__(exceptions.java:278)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.python.core.exceptions$BoundStaticJavaMethod.__call__(exceptions.java:685)
> 	at org.python.core.PyObject.__call__(PyObject.java:446)
> 	at org.python.core.PyBaseExceptionDerived.__str__(PyBaseExceptionDerived.java:65)
> 	at org.python.core.PyString.str_new(PyString.java:172)
> 	at org.python.core.PyString$exposed___new__.new_impl(Unknown Source)
> 	at org.python.core.PyType.invokeNew(PyType.java:1119)
> 	at org.python.core.PyType.type___call__(PyType.java:2399)
> 	at org.python.core.PyType.__call__(PyType.java:2389)
> 	at org.python.core.PyObject.__call__(PyObject.java:461)
> 	at org.python.core.PyObject.__call__(PyObject.java:465)
> 	at org.python.pycode._pyx0.f$0(/home/xxm/Desktop/IFuzzer/bugs/Jython/14241.py:3)
> 	at org.python.pycode._pyx0.call_function(/home/xxm/Desktop/IFuzzer/bugs/Jython/14241.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:173)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1687)
> 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297)
> 	at org.python.util.jython.runSimpleFile(jython.java:365)
> 	at org.python.util.jython.runStream(jython.java:397)
> 	at org.python.util.jython.runFile(jython.java:422)
> 	at org.python.util.jython.main(jython.java:617)
> java.lang.NullPointerException: java.lang.NullPointerException
