### ISSUE TITLE
Jython crashes when running ast.parse() with large expression size.

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#110]
Calling function ast.parse() with large size computation of n e.g. n> 100000 can cause crashes of Jython. 

test.py
```
import ast
mylist = []
n = 100000
print(ast.parse("mylist"+"+mylist"*n))
```

Crash report:
> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     print(ast.parse("mylist"+"+mylist"*n))
>   File "/usr/share/jython/Lib/ast.py", line 37, in parse
>     return compile(expr, filename, mode, PyCF_ONLY_AST)
> java.io.IOException: Resetting to invalid mark
> 	at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
> 	at org.python.core.ParserFacade.readEncoding(ParserFacade.java:390)
> 	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:297)
> 	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:352)
> 	at org.python.core.ParserFacade.parse(ParserFacade.java:196)
> 	at org.python.core.CompileFunction.compile(__builtin__.java:1512)
> 	at org.python.core.CompileFunction.compile(__builtin__.java:1488)
> 	at org.python.core.CompileFunction.__call__(__builtin__.java:1476)
> 	at org.python.core.PyObject.__call__(PyObject.java:441)
> 	at org.python.core.PyObject.__call__(PyObject.java:447)
> 	at ast$py.parse$1(/usr/share/jython/Lib/ast.py:37)
> 	at ast$py.call_function(/usr/share/jython/Lib/ast.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
> 	at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
> 	at org.python.core.PyBaseCode.call(PyBaseCode.java:127)
> 	at org.python.core.PyFunction.__call__(PyFunction.java:317)
> 	at org.python.pycode._pyx0.f$0(/home/xxm/Desktop/IFuzzer/bugs/Jython/32758.py:4)
> 	at org.python.pycode._pyx0.call_function(/home/xxm/Desktop/IFuzzer/bugs/Jython/32758.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1275)
> 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
> 	at org.python.util.jython.run(jython.java:247)
> 	at org.python.util.jython.main(jython.java:129)
> 
> java.io.IOException: java.io.IOException: Resetting to invalid mark
> 

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by xiaxinmeng** [comment]
This case still crashes Jython master (Jython 2.7.3a1-DEV) with the same crash report.
