### ISSUE TITLE
Unfound SAXParser crashes Jython

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#114]
See the following example. In ParserCreate(), SAXParser is not found leading to crashes of Jython.

test.py 
```
from xml.parsers.expat import *
p = ParserCreate()
p.__setattr__(range(0xF), 0)

```

crash report:

> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py 
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 2, in <module>
>     p = ParserCreate()
>   File "/usr/share/jython/Lib/xml/parsers/expat.py", line 59, in ParserCreate
>     return XMLParser(encoding, namespace_separator)
>   File "/usr/share/jython/Lib/xml/parsers/expat.py", line 91, in __init__
>     self._reader = XMLReaderFactory.createXMLReader(_xerces_parser_name)
> java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
> 	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
> 	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:221)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
> org.xml.sax.SAXException: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
> java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
> 

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by xiaxinmeng** [comment]
This bug has been fixed in the master.  Jython 2.7.3a1-DEV does not crash anymore!
