### ISSUE TITLE
Misuse of slice crashes Jython

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#115]
In the following example, the misuse of slice of b crashes Jython interpreter. Jython reports java.lang.IndexOutOfBoundsException 

test.py
```
class X:
    def __index__(self):
        b[:] = [1, 2, 3]
        return 2

b = [123]*0x1000
print(b[0:64:X()])


```
crash report:

> 
> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py 
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 7, in <module>
>     print(b[0:64:X()])
> java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
> 	at java.util.ArrayList.get(ArrayList.java:435)
> 	at org.python.core.PyList.getslice(PyList.java:1182)
> 	at org.python.core.PySequence$1.getSlice(PySequence.java:462)
> 	at org.python.core.SequenceIndexDelegate.getSlice(SequenceIndexDelegate.java:80)
> 	at org.python.core.PySequence.seq___getslice__(PySequence.java:324)
> 	at org.python.core.PySequence.__getslice__(PySequence.java:320)
> 	at org.python.pycode._pyx0.f$0(/home/xxm/Desktop/IFuzzer/bugs/Jython/27867.py:7)
> 	at org.python.pycode._pyx0.call_function(/home/xxm/Desktop/IFuzzer/bugs/Jython/27867.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1275)
> 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
> 	at org.python.util.jython.run(jython.java:247)
> 	at org.python.util.jython.main(jython.java:129)
> 
> java.lang.IndexOutOfBoundsException: java.lang.IndexOutOfBoundsException: Index: 4, Size: 3

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by xiaxinmeng** [comment]
This case also crashes Jython 2.7.3a1-DEV with the same crash report.

**Comment by jeff5** [comment]
Obviously this procession of reports is the result of automated fuzzing. I suppose one ought to be grateful. :/ It certainly turns up cases where our logic could be improved, as in the present case where the length of the list changes by side effect while we are calculating the indices using the handy [PySlice.indicesEx](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/core/PySlice.java#L116).

I would say the project has not tried to be as bullet-proof would be necessary to withstand this kind of systematic abuse. Do you have a use-case where crashing out of the JVM would be such a bad thing?
