### ISSUE TITLE
exec() takes too long computation crashes Jython.

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#116]
Calling function ast.parse() with large size computation of n e.g. n> 100000 can cause crashes of Jython. 

test.py
```
import ast
mylist = []
exec("mylist"+"+mylist"*100000)

```

crash report

> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py 
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     exec("mylist"+"+mylist"*100000)
> java.io.IOException: Resetting to invalid mark
> 	at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
> 	at org.python.core.ParserFacade.readEncoding(ParserFacade.java:390)
> 	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:297)
> 	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:352)
> 	at org.python.core.ParserFacade.parse(ParserFacade.java:196)
> 	at org.python.core.Py.compile_flags(Py.java:1751)
> 	at org.python.core.Py.exec(Py.java:1316)
> 	at org.python.pycode._pyx0.f$0(/home/xxm/Desktop/IFuzzer/bugs/Jython/32758.py:4)
> 	at org.python.pycode._pyx0.call_function(/home/xxm/Desktop/IFuzzer/bugs/Jython/32758.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1275)
> 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
> 	at org.python.util.jython.run(jython.java:247)
> 	at org.python.util.jython.main(jython.java:129)
> 
> java.io.IOException: java.io.IOException: Resetting to invalid mark
> 

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by xiaxinmeng** [comment]
This case also crashes Jython 2.7.3a1-DEV with the same crash report.

**Comment by jeff5** [comment]
Not really to do with `exec()` so much as the parser not coping with the overly long line. If I remember rightly there's a fixed-size buffer where we normalise the encoding of the source.

I'm comforted that CPython (3.8.5 on Windows) is actually worse.

    python -c "code = compile('mylist'+'+mylist'*100000, '<string>', 'exec'); print(type(code))"

just exists silently on my machine.

**Comment by xiaxinmeng** [comment]
Yes, CPython  has also suffered this bug, but it is fixed on the latest version. You can try the master.(3.11) Only RecursionError is reported now.
