### ISSUE TITLE
sort() cause jython crashing with java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#118]
See the following example. gl calls the function sort() and then Jython crashes.

test.py

```
class C:
    def __cmp__(self, other):
        pop(0)
        return 1
gl = [C() for i in '1'*20]
pop=gl.pop
gl.sort()

```

crash report:

> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 7, in <module>
>     gl.sort()
> java.lang.NullPointerException
> 	at org.python.core.PyList$PyObjectDefaultComparator.compare(PyList.java:773)
> 	at org.python.core.PyList$PyObjectDefaultComparator.compare(PyList.java:764)
> 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
> 	at java.util.TimSort.sort(TimSort.java:220)
> 	at java.util.Arrays.sort(Arrays.java:1512)
> 	at java.util.ArrayList.sort(ArrayList.java:1464)
> 	at java.util.Collections.sort(Collections.java:177)
> 	at org.python.core.PyList.sort(PyList.java:757)
> 	at org.python.core.PyList.sort(PyList.java:737)
> 	at org.python.core.PyList.list_sort(PyList.java:730)
> 	at org.python.core.PyList$list_sort_exposer.__call__(Unknown Source)
> 	at org.python.core.PyObject.__call__(PyObject.java:371)
> 	at org.python.core.PyObject.__call__(PyObject.java:375)
> 	at org.python.pycode._pyx0.f$0(/home/xxm/Desktop/IFuzzer/bugs/Jython/453523.py:7)
> 	at org.python.pycode._pyx0.call_function(/home/xxm/Desktop/IFuzzer/bugs/Jython/453523.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1275)
> 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
> 	at org.python.util.jython.run(jython.java:247)
> 	at org.python.util.jython.main(jython.java:129)
> 
> java.lang.NullPointerException: java.lang.NullPointerException
> 

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292
>

**Comment by xiaxinmeng** [comment]
This case  crashes Jython 2.7.3a1-DEV in the same way.
