### ISSUE TITLE
Import Error deserializing PyCode object

### ISSUE THREAD

**Issue by sarashinai** [jython/jython#153]
Hello,
  I also posted this to https://stackoverflow.com/questions/71229813/jython-reading-pycode-object-from-file-importerror-no-module-name-pycode

I am using Jython to run Python code inside of my Java app. I am testing to see if I can compile some Python code to a PyCode object, serialize it, deserialize it, and then run it. Everything I've read suggests that I should be able to do this but I keep hitting an error I don't understand. I have attempted to create a smallest possible example to demonstrate what I'm doing (see code block below). I have included the output I'm receiving, as well.

```
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import org.python.core.PyCode;
import org.python.util.PythonInterpreter;
import org.python.util.PythonObjectInputStream;

public class Main {
    public static void main(String[] args) throws Exception {
        PythonInterpreter pi = new PythonInterpreter();

        try {
           PyCode code = pi.compile("print('compiled!')");
           System.out.println("Code: %s".formatted(code));

           pi.exec(code);

           OutputStream os = Files.newOutputStream(Paths.get("compiled_code"), StandardOpenOption.CREATE);
           System.out.println("os: %s".formatted(os));

           ObjectOutputStream oos = new ObjectOutputStream(os);
           System.out.println("oos: %s".formatted(oos));

           oos.writeObject(code);
           oos.close();

           InputStream is = Files.newInputStream(Paths.get("compiled_code"), StandardOpenOption.READ);
           System.out.println("is: %s".formatted(is));

           ByteArrayInputStream bais = new ByteArrayInputStream(is.readAllBytes());
           System.out.println("bais: %s".formatted(bais));

           PythonObjectInputStream pois = new PythonObjectInputStream(bais);
           System.out.println("pois: %s".formatted(pois));

           code = (PyCode)pois.readObject();
           System.out.println("Code: %s".formatted(code));

           pois.close();
              
           pi.exec(code);
        }            
    }
}
```

This is the output. As you can see, it doesn't execute the second time and the error seems to be from within Python rather than from an IO issue. It seems to throw the exception from ```readObject()```

```
Code: <code object <module> at 0x2, file "<script>", line 0>
compiled!
os: java.nio.channels.Channels$1@3bbf9027
oos: java.io.ObjectOutputStream@15e0fe05
is: sun.nio.ch.ChannelInputStream@41bf79da
bais: java.io.ByteArrayInputStream@1a891add
pois: org.python.util.PythonObjectInputStream@62a4417
Exception: ImportError: No module named pycode
```

I'd be very grateful for any support that can be provided.

**Comment by sarashinai** [comment]
Could I get a little in-house feedback, if possible? Is this a bug? Is this a coding/understanding error on my part?

**Comment by jeff5** [comment]
The problem arises where the `PythonObjectInputStream` tries to resolve the class `org.python.pycode._pyx0`. The package `org.python.pycode` is just an artefact of the compiler. When the JVM cannot find it, it tries to find a Python module, which also fails. The message is from this second failure, so a little misleading.

It surprises me it cannot find the class, because it must have found it to execute `code` the first time. However, it would not help to solve that, since you presumably want to write this from one programme and read it in another.

I think you need to get hold of the byte code representation of the class generated by the compiler. Also [clamp](https://github.com/groves/clamp) would be worth a look.

------

I found this is a useful command (in the dev environment) to explore the issue:
```
java -classpath "dist\jython-dev.jar;dist\javalib\*;." "-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y" "-Dpython.home=dist" Main
```

I adapted the code to run on earlier Java than 17:
```
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import org.python.core.PyCode;
import org.python.util.PythonInterpreter;
import org.python.util.PythonObjectInputStream;

public class Main {

    public static void main(String[] args) throws Exception {
        try (PythonInterpreter pi = new PythonInterpreter()) {

            PyCode code = pi.compile("print('compiled!')");
            System.out.println(String.format("Code: %s", code));

            pi.exec(code);

            OutputStream os =
                    Files.newOutputStream(Paths.get("compiled_code"), StandardOpenOption.CREATE);
            System.out.println(String.format("os: %s", os));

            ObjectOutputStream oos = new ObjectOutputStream(os);
            System.out.println(String.format("oos: %s", oos));

            oos.writeObject(code);
            oos.close();

            InputStream is =
                    Files.newInputStream(Paths.get("compiled_code"), StandardOpenOption.READ);
            System.out.println(String.format("is: %s", is));

            byte[] ba = new byte[is.available()];
            is.read(ba);
            ByteArrayInputStream bais = new ByteArrayInputStream(ba);
            System.out.println(String.format("bais: %s", bais));

            PythonObjectInputStream pois = new PythonObjectInputStream(bais);
            System.out.println(String.format("pois: %s", pois));

            code = (PyCode) pois.readObject();
            System.out.println(String.format("Code: %s", code));

            pois.close();

            pi.exec(code);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

**Comment by sarashinai** [comment]
I've run your adapted code in my environment with the same result, so we need it duplicates it. How do I get the byte code representation to show you? Also, where does clamp fit into this?

**Comment by jeff5** [comment]
I think we can see that de-serialising a `PyCode` doesn't work. I was going to suggest `pickle`, but Jython won't pickle a `code` object either. There must be a half-good reason but it would be nice if Jython 3 didn't have that restriction.

> I've run your adapted code in my environment with the same result,

Yes. We do not test Jython on Java 17, so I wanted to see it on a supported JVM.

> How do I get the byte code representation to show you? Also, where does clamp fit into this?

I am probably guessing incorrectly what your aim is. Forget `clamp` for now.

I don't want to see the bytecode. The result of compilation is a Java class definition as bytes. In this context the class definition is ephemeral, but if we break down how a module gets loaded from source, we can get at the bytes between compilation and building the `PyCode`:
```
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;

import org.python.core.BytecodeLoader;
import org.python.core.PyCode;
import org.python.core.imp;
import org.python.util.PythonInterpreter;

public class MainByteCode {

    public static void main(String[] args) throws Exception {
        try (PythonInterpreter pi = new PythonInterpreter()) {

            String sourceString = "print 'compiled!'";
            String name = "mymodule";

            // Dress the String as bytes: compiler not v good with encodings.
            InputStream source = new InputStream() {
                ByteBuffer buf = StandardCharsets.US_ASCII.encode(sourceString);
                @Override
                public int read() throws IOException {
                    if (buf.remaining() > 0) {
                        return buf.get() & 0xff;
                    } else {
                        return -1;
                    }
                }
            };

            byte[] javaCode = imp.compileSource(name, source, "<string>");
            String className = name + "$py";

            PyCode code = BytecodeLoader.makeCode(className, javaCode, "<string>");
            System.out.println(String.format("Code: %s", code));
            pi.exec(code);

            // You can write a file and read it back if you want :)
            byte[] javaCode2 = javaCode.clone();

            PyCode code2 = BytecodeLoader.makeCode(className, javaCode2, "<file>");
            System.out.println(String.format("Code: %s", code2));
            pi.exec(code2);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by sarashinai** [comment]
I really DO appreciate your help, solving this is pretty important to what I'm trying to do. My purpose is to use Java as a GUI shell wrapped around the Jython PythonInterpreter and to use Python as the internal scripting language. Ideally, I would be able to encapsulate all of the data, including compiled python code, to distribute and to be loadable by others with the shell. When I couldn't solve this, I embarked on zipping the code folder into memory and then pickling the resulting zip with other relevant data. Unfortunately, I ran into problems has the interpreter access the zipped code. I built a meta_path importer to resolve that, but have run into interpret-time issues with global names not being found for modules and classes imported from those files. It's possible I'll still face the same problem even with pre-compiled code but I won't know until I get it working.

I may have garbled things when I changed it to read and write from a file (let me know if you spot an error I've introduced).

```
    public static void main(String[] args) throws Exception {
        try (PythonInterpreter pi = new PythonInterpreter()) {

            String sourceString = "print 'compiled!'";
            String name = "mymodule";

            // Dress the String as bytes: compiler not v good with encodings.
            InputStream source = new InputStream() {
                ByteBuffer buf = StandardCharsets.US_ASCII.encode(sourceString);
                @Override
                public int read() throws IOException {
                    if (buf.remaining() > 0) {
                        return buf.get() & 0xff;
                    } else {
                        return -1;
                    }
                }
            };

            byte[] javaCode = imp.compileSource(name, source, "<string>");
            String className = name + "$py";

            PyCode code = BytecodeLoader.makeCode(className, javaCode, "<string>");
            System.out.println(String.format("Code: %s", code));
            pi.exec(code);

            // You can write a file and read it back if you want :)
            // byte[] javaCode2 = javaCode.clone();
            OutputStream os = Files.newOutputStream(Paths.get("compiled_code"), StandardOpenOption.CREATE);
            System.out.println("os: %s".formatted(os));

            os.write(javaCode);
            os.close();

            InputStream is = Files.newInputStream(Paths.get("compiled_code"), StandardOpenOption.READ);
            System.out.println("is: %s".formatted(is));

            ByteArrayInputStream bais = new ByteArrayInputStream(is.readAllBytes());
            System.out.println("bais: %s".formatted(bais));

            byte[] javaCode2 = bais.readAllBytes();

            bais.close();

            PyCode code2 = BytecodeLoader.makeCode(className, javaCode2, "<file>");
            System.out.println(String.format("Code: %s", code2));
            pi.exec(code2);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

````

Giving output

```
Code: <code object <module> at 0x2, file "<string>", line 0>
compiled!
os: java.nio.channels.Channels$1@ce9b9a9
is: sun.nio.ch.ChannelInputStream@15d0849
bais: java.io.ByteArrayInputStream@4038cd3a
Exception in thread "main" java.lang.ClassFormatError: Extra bytes at the end of class file mymodule$py
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at org.python.core.BytecodeLoader$Loader.loadClassFromBytes(BytecodeLoader.java:313)
	at org.python.core.BytecodeLoader.makeClass(BytecodeLoader.java:37)
	at org.python.core.BytecodeLoader.makeCode(BytecodeLoader.java:249)
	at com.bbg.japyif.Main.main(Main.java:292)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

````

**Comment by jeff5** [comment]
That middle bit you added is almost exactly what I had before I replaced the file i/o with a `clone()`. Except I did not wrap the byte array in a `ByteArrayInputStream`. The bytes in the file are the bytes you want, and you read them all at once. I used `new byte[is.available()];` and a plain `read` in place of `readAllBytes`, because I was running on Java 8.

The error, however is `java.lang.ClassFormatError: Extra bytes at the end of class file mymodule$py`. I don't see why that would be the result of the extra wrapping on the stream or of your use of `readAllBytes`.

If `javaCode2` is not identical to `javaCode` then it's nothing to do with Jython and I'm sure you'll work it out.

If it is identical, it's hard to see how one call to `makeCode` could succeed and the other fail.

It would be worth trying on Java 8 or 11, just in case there is a compatibility issue.

**Comment by sarashinai** [comment]
Two updates:

1. I have tried running my original code (found in the first post) under OpenJDK 11 to check for a compatibility issue as you suggested. Same result, `Exception: ImportError: No module named pycode`. This still strikes me as very strange as it seems to go against the whole point of PythonObjectInputStream to not be able to load a PythonObject.
2. In regards to your later suggestions with `Bytecodeloader.makeCode`, I still don't know why there are more bytes to read from the file than are in the byte array that I write to it. It could be a bug or a part of the Java IO system that I don't understand. However, as long as I read a specific number of bytes in (the number written) rather than using a "readAll", javaCode2 is identical to javaCode and runs correctly.

**Comment by jeff5** [comment]
> 1. ... This still strikes me as very strange as it seems to go against the whole point of PythonObjectInputStream to not be able to load a PythonObject.

Broadly I agree, and doubly when it comes to `marshal` and `pickle`, but I would rather work on Jython 3 than fix that.

> 2. In regards to your later suggestions with `Bytecodeloader.makeCode`, I still don't know why there are more bytes to read from the file than are in the byte array that I write to it. 

No, and I don't experience that problem. It worked for me with the "middle bit" being:
```
            OutputStream os =
                    Files.newOutputStream(Paths.get("compiled_code"), StandardOpenOption.CREATE);
            System.out.println(String.format("os: %s", os));
            os.write(javaCode);
            os.close();

            InputStream is =
                    Files.newInputStream(Paths.get("compiled_code"), StandardOpenOption.READ);
            System.out.println(String.format("is: %s", is));
            //byte[] javaCode2 = new byte[is.available()];
            //is.read(javaCode2);
            byte[] javaCode2 = is.readAllBytes();
            is.close();
```
and compiling (just) `MainByteCode` with Java 17. To be exact, I am on Windows using:
```
PS Jython-2> java --version
java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
PS Jython-2> java -classpath "dist\jython-dev.jar;dist\javalib\*;." "-Dpython.home=dist" MainByteCode
Code: <code object <module> at 0x2, file "<string>", line 0>
compiled!
os: java.nio.channels.Channels$1@7a55f148
is: sun.nio.ch.ChannelInputStream@7f572c37
Code: <code object <module> at 0x3, file "<file>", line 0>
compiled!
```
It even works for me if I wrap an array from `is`in a `ByteArrayInputStream`. So, something is wrong with your setup that isn't Jython.
