### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by bts-webber** [jython/jython#207]
I'm using Jython to develop Flink Java UDF. When I run it, I get an error:

> org.apache.flink.runtime.taskmanager.Task                    [] - Source: TableSourceScan(table=[[vvp, default, dwd_yunsec_host_aegis_proc_inner_s ... with job vertex id 717c7b8afebbfb7137f6f0f99beb2a94 (6/20)#0 (230a68259cc3877ac6b2be2ec4d7d299) switched from INITIALIZING to FAILED with failure cause: java.lang.IllegalArgumentException: URI is not hierarchical
> 	at java.io.File.<init>(File.java:420)
> 	at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427)
> 	at org.python.core.PrePy._getJarFileName(PrePy.java:362)
> 	at org.python.core.PrePy.getJarFileName(PrePy.java:345)
> 	at org.python.core.PySystemState.doInitialize(PySystemState.java:1195)
> 	at org.python.core.PySystemState.initialize(PySystemState.java:1130)
> 	at org.python.core.PySystemState.initialize(PySystemState.java:1085)
> 	at org.python.core.PySystemState.initialize(PySystemState.java:1080)
> 	at org.python.core.PySystemState.initialize(PySystemState.java:1075)
> 	at org.python.core.PySystemState.initialize(PySystemState.java:1070)
> 	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
> 	at org.python.core.Py.getThreadState(Py.java:1741)
> 	at org.python.core.Py.getThreadState(Py.java:1737)
> 	at org.python.core.Py.getSystemState(Py.java:1757)
> 	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
> 	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
> 	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
> 	at sangduo.factory.JythonObjectFactory.createObject(JythonObjectFactory.java:31)
> 	at sangduo.udfx.CmdlineNormal.CmdlineNormalTest(CmdlineNormal.java:28)
> 	at sangduo.udfx.CmdlineNormal.open(CmdlineNormal.java:32)
> 	at StreamExecCalc$9384.open(Unknown Source)
> 	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:444)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:586)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.call(StreamTaskActionExecutor.java:100)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeRestore(StreamTask.java:566)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:651)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:541)
> 	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
> 	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:586)
> 	at java.lang.Thread.run(Thread.java:877)

At org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427)，value of **fileURI** is:
`file:../userlib/jython-standalone-2.7.2-fix.jar!/org/python/core/PrePy.class`

At line 431 ，**new File(fileURI)**  , if URI is not Absolute will raise this error.

I will submit some code to fix this issue: Convert URI to absolute path before return.

**Comment by jeff5** [comment]
Take a look at #25. That may be a work-around.

However, if it is to be fixed according to expectations, we need a simple way to reproduce it in isolation from complex applications. Only the people discussing seem to understand it :(

Edit: ah, looks like you may be offering a patch.

**Comment by jeff5** [comment]
I'm not knowlegeable enough in JBoss to know for sure, but relative references in VFS seem to be rare to non-existent, and if used, are interpreted [relative to some a root of the VFS](https://docs.jboss.org/jbossas/javadoc/7.1.2.Final/org/jboss/vfs/VFS.html#mount(org.jboss.vfs.VirtualFile,%20org.jboss.vfs.spi.FileSystem)), not to the current working directory.
