### ISSUE TITLE
httplib connections no longer support unicode

### ISSUE THREAD

**Issue by tpoliaw** [jython/jython#211]
We have recently updated from 2.7.1 to 2.7.3 and have found a regression in how httplib handles unicode

```
import httplib

def post(data):
    try:
        conn = httplib.HTTPSConnection('httpbin.org')
        conn.request('POST', '/post', data)
        resp = conn.getresponse()
        print(resp.read())
    finally:
        conn.close()


post('this is a string')
post(u'this is unicode')
```

Running this with jython 2.7.1 gives the response for both calls. For 2.7.3, the first is successful but the second fails with 
```
Traceback (most recent call last):
  File "/tmp/http_demo.py", line 14, in <module>
    post(u'this is unicode')
  File "/tmp/http_demo.py", line 6, in post
    conn.request('POST', '/post', data)
  File "/tmp/jython-standalone-2.7.3.jar/Lib/httplib$py.class", line 1082, in request
  File "/tmp/jython-standalone-2.7.3.jar/Lib/httplib$py.class", line 1122, in _send_request
  File "/tmp/jython-standalone-2.7.3.jar/Lib/httplib$py.class", line 1078, in endheaders
  File "/tmp/jython-standalone-2.7.3.jar/Lib/httplib$py.class", line 898, in _send_output
  File "/tmp/jython-standalone-2.7.3.jar/Lib/httplib$py.class", line 870, in send
  File "/tmp/jython-standalone-2.7.3.jar/Lib/ssl$py.class", line 740, in sendall
  File "/tmp/jython-standalone-2.7.3.jar/Lib/_socket$py.class", line 1459, in meth
  File "/tmp/jython-standalone-2.7.3.jar/Lib/_socket$py.class", line 0, in sendall
TypeError: cannot make memory view because object does not have the buffer interface
```
This appears to be a consequence of #185 and PyUnicode [only superficially implementing `BufferProtocol`](https://github.com/jython/jython/blob/26731ea801a15feb86955e5284e61b8fb71ee306/src/org/python/core/PyUnicode.java#L183).

**Comment by krismarc** [comment]
Any update on this? I have just experienced the same. If I convert the payload to bytes then it works "bytes(payload)".
However, currently I am not sure how to deal with.
```
url = httplib.HTTPConnection(host)
url.endheaders()
```

```
Traceback (most recent call last):
  File "/opt/wlp/integration/deployment/sr-wlp-deploy/utilities/sr_http_util.py", line 169, in http_invoke
    url.endheaders()
  File "/opt/wlp/integration/jython/jython_273rc1/Lib/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/opt/wlp/integration/jython/jython_273rc1/Lib/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/opt/wlp/integration/jython/jython_273rc1/Lib/httplib.py", line 870, in send
    self.sock.sendall(data)
  File "/opt/wlp/integration/jython/jython_273rc1/Lib/ssl.py", line 740, in sendall
    return self.sock.sendall(data)
  File "/opt/wlp/integration/jython/jython_273rc1/Lib/_socket.py", line 1459, in meth
    return getattr(self._sock,name)(*args)
  File "/opt/wlp/integration/jython/jython_273rc1/Lib/_socket.py", line 0, in sendall
TypeError: cannot make memory view because object does not have the buffer interface
```

I can confirm it works well with previous 2.7.2 version.

**Comment by jeff5** [comment]
It is clear that `httplib`, which we inherit unmodified from CPython `stdlib`, takes a very stringy approach to the content, and the docs make no mention of unicode, while of course `str`-strings in Python 2.7 are bytes.

https://github.com/jython/jython/blob/ad164ef3163d38591b79ee4ce4dd367779d0541f/lib-python/2.7/httplib.py#L879-L898

`_socket` definitely assumes bytes. The corresponding CPython module assumes that too, I think, although our implementation is quite difficult to compare.

Jython originally tried to stretch `str` to the range of UTF-16, but we have had to back off in order to be more compatible. This has left all sorts of sharp edges. What happens when you mix `str`and `unicode` is a little hard to predict, but mostly there will be promotion to `unicode`.

I would not expect Jython ever to have got the correct result here with a Unicode string above 8 bits. If you want to support Unicode with something that is essentially a channel for bytes, the explicit encoding is advisable.

@krismarc : Thanks for the stack trace, that's useful. I don't understand why an empty `.endheaders` is producing that `TypeError`. WIBNI type errors came with a bit more information (like a type)? I wonder if previous operations have somehow promoted a buffer string to `unicode`?

**Comment by krismarc** [comment]
Some headers were added there just before using endheaders function. Next week I can drop more details.

The question is what changed between jython 2.7.2 and 2.7.3 so it started resulting in such an error.

**Comment by jeff5** [comment]
> The question is what changed between jython 2.7.2 and 2.7.3 so it started resulting in such an error.

What changed is use of the buffer interface to accept a wider range of byte-like data without copying. @tpoliaw has identified the change, but the change should be ok if one understands the specification to be "accept byte data". (The word "specification" is often an overstatement when it comes to Python.)

The change may be revealing a latent problem whereby `unicode` is supplied to the interface that now only accepts bytes.

**Comment by krismarc** [comment]
Just to make things clear. Does it mean we have to live with this and adjust the code where we use httplib to pass bytes? :)

**Comment by jeff5** [comment]
I can't tell what the intended behaviour of the library is with respect to unicode. In the absence of a clear specification, we try to make Jython do what CPython 2.7 does. I've marked this as a bug pending comparison.

It is documented to work with `str`, and there is no explicit support for encoding, so doing ones own encoding is the safe choice.

**Comment by krismarc** [comment]
It seems to be fixed in 2.7.4 :) thanks for taking care!

**Comment by jeff5** [comment]
It got a mention in #256, but it didn't close automatically. Thanks for reminding us and confirming from the field.
