### ISSUE TITLE
Clarification on compile 

### ISSUE THREAD

**Issue by yogi1967** [jython/jython#234]
Apologies this isn't as such an issue report, but seeking clarification: Jython 2.7.x

For reasons outside of my control, I am forced to use single, large script files.. I write extensions to an app which controls the environment my code executes in (code is started / run by the master app through PythonInterpreter). 

I cannot do 'normal' imports as my code runs from within a ZIP file. I can get the zip resources and contents via classloader.getResourceAsStream() etc.

Because I have large files, I sometimes hit the:
java.lang.RuntimeException: Module or method too large in xxx.py

and it then says:

Please provide a CPython 2.7 bytecode file (.pyc), e.g. run
python -m py_compile xxx.py

Alternatively, specify a CPython 2.7 command via the python.cpython2 property, e.g.:
    jython -Dpython.cpython2=python
or (e.g. for pip) through the environment variable JYTHON_OPTS:

----
So, question 1. Why is it saying use python -m for jython?

question 2: is it actually possible to create .pyc files for jython, and if so, how do you actually do it?

question 3: what is the difference between .pyc files and xxx$py.class files?

I have now managed to compile jython using: 
java -cp jython.jar org.python.util.jython -c "import compileall; compileall.compile_file('xx.py')"
.. and run it using imp.load_module() so this bit is great! But of course the script ends up within a sub module scope whereas I really want it within the scope of the original script. (Hence execfile would be  more useful). 

question 4: is there a way to execute $py.class files using execfile() via a resource stream (like load_module) rather than from a file?

question 5: I see exec can run Code objects.... What is this Code object? Is it the same as a .pyc file and/or $py.class file? And again, can a stream be executed rather than a file....?

Separately, I have seen that execfile() on a script which hits the too large issue, does actually run if a .pyc is also present on disk in the same location and one that was compiled by python -m py_compile... So something with pyc works... This all seems very odd..!?

Sorry for the questions, I have done much reading and experimenting. I am glad I have finally got something working, but your clarification(s) would be appreciated? 

Thanks

**Comment by Stewori** [comment]
On short time, so just the essentials:
Jython *can* read and execute CPython's (2.7) bytecode pyc files, but it cannot generate them. $py.class files is Jython's original way of bytecode, i.e. compile to Java bytecode. Support of pyc files is just an additional feature. Jython had frequent issues due to limited method length in Java's bytecode spec. Using the pyc file support is a workaround for that.

**Comment by yogi1967** [comment]
Thanks! Wow, so python can read CPython bytecode files and this is fully supported?! A few clarification questions:
- so is a pyc better than a $py.class file, or visa-versa, or are they the same? I’m after the fastest launch time, that avoids Jython doing extra checks/compiles and one that avoids the method limit issue. 
- if you use a pyc, does jython then compile that further to a $py.class file internally anyway. Ie what is the final destination compile for all code?
- Do both pyc and $py.class fix/get around the method length issue?
- Can imp.load_module execute both pyc and $py.class compiled files?
- Can exec and execfile execute both pyc and $py.class compiled files?
- If jython3 ever arrives, will both pyc and $py.class be supported?


Thanks!

**Comment by Stewori** [comment]
I think $py.class is more performant since it is native to Java. pyc files are not further compiled, but *interpreted* by Jython. They result in a different PyCode subclass (I think pyc->PyBytecode and $py.class -> PyTableCode).
However, in presence of oversized Python functions I once implemented a smarter approach:
A $py.class cannot be compiled in that case because the limitation lies in Java's bytecode format and is therefore inherent.
If a pyc file can be found or created via a specified CPython 2.7 command, the necessary bytecode is taken from the pyc (only for the Functions in question) and *embedded* into the resulting $py.class via String constants. Due to the base64 encoding, the resulting class files may be unusually large, but I suppose jar-compression can compensate that. That means, if Jython succeeds in creating a $py.class file for a module, the pyc file does not have to be distributed. It only enables creation of the $py.class file initially. Regarding imp.load_module and exec, execfile I do not know right now and would have to look it up or try for myself. Regarding Jython3 I think it will be pyc first and Java bytecode eventually.

**Comment by yogi1967** [comment]
OMG! So, I now generate a .pyc using:
python -m x.py
and then generate a class file using 
java -cp jython.jar org.python.util.jython -c "import compileall; compileall.compile_file() x.py
... and the .pyc being present allows the java class compile to work (when before it was method too large) and as you say, I can just distribute the .class... Excellent!

I think this needs to be documented somewhere!?

Thanks for your help!

**Comment by Stewori** [comment]
Exactly! You can alternatively configure `-Dpython.cpython2=python`, then Jython does the `python -m x.py` part automatically as needed. That is intended for large projects where many files are affected and it would be a hassle to sort things out manually.

> I think this needs to be documented somewhere!?

Only in the news file and by means of the instructions in the error message AFAIK.

**Comment by yogi1967** [comment]
Hmm... Where do you do this:
-Dpython.cpython2=python
??
Is this on Jython/JVM launch..? If so, I cannot use this as my code runs within a master app that I have no control over... This is an extension.....

**Comment by yogi1967** [comment]
.. and just in time. After I got all this plumbed up, today my script hit the method too large issue and my new .pyc and $py.class build saved the day. Thanks!!

**Comment by Stewori** [comment]
Welcome!
> Where do you do this

Yes, on the jvm startup command line. If that is not an option you can set it in the Jython registry file, see
https://www.jython.org/registry.html
Maybe you can also set it programmatically. It should reside in PySystemState.registry (a Properties object), but I am not sure whether that is  writable.

**Comment by yogi1967** [comment]
Got it. I see where to put the -D command. Due to my environment setup, I can’t use that. But doesn’t matter as the python -m command works well. Thanks. 

Now, last step. To see if I can use execfile() with a stream pointing to the $py.class file (instead of script) - rather than just imp.load_module().

**Comment by yogi1967** [comment]
So.. final question in this thread... I would love to be able to run execfile() on the compiled $py.class file, rather than imp.load_module()... Why? Well really for namespace reasons so that the code runs in the same namespace as it would if I could just execfile() the file (as I can do for non compiled scripts)... (for example, the master application which I have no control over sets key variables for my script to read, but if I import my script, and use load_module(), I have to trick the passing of these variables to the new module by stuffing them into __builtin__ as globals() is not shared... Same goes for passing back info to the master application....) But as my script's method(s) are too large now for running uncompiled, they must be compiled.... I see all routes for execfile() eventually lead to Py.runCode() but it requires a PyCode object  - I have no idea how to get a $py.class file into a PyCode object.... TIA!

**Comment by Stewori** [comment]
> how to get a $py.class file into a PyCode object

I think that's done with `org.python.core.BytecodeLoader.makeCode`. It requires the class file loaded into a Java byte array.

**Comment by yogi1967** [comment]
Thank you! It works.. The code to execute compiled $py.class file from a stream is as follows:

```
_launchedFile = _THIS_IS_ + _compiledExtn
scriptStream = MD_EXTENSION_LOADER.getResourceAsStream(u"/%s" %(_launchedFile))
code = BytecodeLoader.makeCode(os.path.splitext(_launchedFile)[0], IOUtils.toByteArray(scriptStream), (_THIS_IS_ + _normalExtn))
scriptStream.close()
exec(code)
```

Excellent. Many thanks for your help!

**Comment by jeff5** [comment]
> * If jython3 ever arrives, will both pyc and $py.class be supported?

If it ever does, it will almost certainly interpret CPython byte/word code (`.pyc` files) from the compatible version of CPython. It [already does to a limited extent](https://github.com/jython/jython/blob/main/core/src/main/java/org/python/core/CPython38Frame.java). And it wouldn't be Jython if it didn't compile to JVM byte code.

**Comment by yogi1967** [comment]
Thanks Jeff!

**Comment by yogi1967** [comment]
One very last question. Is is possible to use imp.load_module() to import the code into the current namespace, rather that it creating a 'module' and importing it into that? Thanks.

**Comment by yogi1967** [comment]
Hi @jeff5... A quick followup question if you don't mind... As above, I am using this code to launch a compiled script:

```
_launchedFile = _THIS_IS_ + _compiledExtn
scriptStream = MD_EXTENSION_LOADER.getResourceAsStream(u"/%s" %(_launchedFile))
code = BytecodeLoader.makeCode(os.path.splitext(_launchedFile)[0], IOUtils.toByteArray(scriptStream), (_THIS_IS_ + _normalExtn))
scriptStream.close()
exec(code)

```
It works great..! Just one small niggle.. In the stack trace, it's referred to as `"<iostream>"`.

If I use PythonInterpreter.execfile() then there is an argument name that allows you to pass the name. But I cannot see how to do this when using the exec statement... And I cannot see how to do run the code any other way.. I.e. there appears to be no way to use PythonInterpreter.execfile() passing the PyCode object..

Any ideas? Many thanks

**Comment by jeff5** [comment]
Glad that works.

In this call, the file name you give is supposed to make its way to the constructor that returns a Python `code` object. I don't immediately see where it might be being lost as it is in generated code.

By comparison, in `execfile` the name is given to the compiler (and not to `runCode`) so it must be embedded in the class it generates (maybe as `__file__`). It could be we're only testing for (so only supporting) this case, which seems like a bug ... or not what was intended in the design of `makeCode`.

Do you mean the Python stack trace?

**Comment by yogi1967** [comment]
Hi @jeff5 - ignore this.. It seems OK now. I must have done something wrong that day. Sorry to bother you with this! Thanks again.... S

**Comment by yogi1967** [comment]
@jeff5  - A further question.. I am using import compileall; compileall.compile_file method. This is all OK and great... However I may have hit an issue with the byte code version.. What bytecode version .class file does this create? Is there a way to specify a byte code version in the method call, and/or a way to call this using latest JDK but to specify the version (like you can do with javac)? Thanks

**Comment by yogi1967** [comment]
... in fact, looking at the raw file, it looks like it's bytecode version: 50.0 (Java 6).. So that's OK.. Is this fixed in the compiler no matter what JDK you run? Thanks....

**Comment by Stewori** [comment]
Classfiles are created using [asm](https://asm.ow2.io/). One would have to look into the way Jython calls asm and what config asm offers. I suspect we are just calling it with default settings, but didn't look it up. As a side note, maybe the asm dependency could do with an update to support latest bytecode version.

**Comment by yogi1967** [comment]
This may be a rabbit hole... Can you point me to the Class/Method that is making the asm call, and I will look from there.. I've tried to find it, but got lost... Sorry.... thx

**Comment by jeff5** [comment]
(I'm a little lost in the code generator myself.) I accuse:
https://github.com/jython/jython/blob/e55e057637eb9fa30710f4c6720186a37c2b8974/src/org/python/compiler/ClassFile.java#L242

I *may* have thought that this:
https://github.com/jython/jython/blob/e55e057637eb9fa30710f4c6720186a37c2b8974/src/org/python/compiler/Code.java#L25
would set a minimum JVM of 7 (could be 8 now), but it doesn't.

**Comment by yogi1967** [comment]
@Stewori @jeff5 

Hello, sorry for a followup question... I've been using these compile tasks to generate .pyc -> .class files for a while. This avoids the method too large error. My files are large and run in a locked 'master' app as extensions... We just upgraded the jython to 2.7.4 (from 2.7.2) and some of my compiled extensions (well only one) fails to launch with 

```
Error: java.lang.RuntimeException: java.lang.RuntimeException: java.io.InvalidClassException: org.python.core.PyString; local class incompatible: stream classdesc serialVersionUID = -2986619840108826351, local class serialVersionUID = 5000969101243649193
Traceback (most recent call last):
  File "extension(toolbox):toolbox_bootstrap.py", line 121, in <module>
  File "extension(toolbox):toolbox_bootstrap.py", line 121, in <module>
	at org.python.core.BytecodeLoader.makeClass(BytecodeLoader.java:43)
	at org.python.core.BytecodeLoader.makeCode(BytecodeLoader.java:249)

```

The load code is this
```
        import os
        from org.python.core import BytecodeLoader
        from org.python.apache.commons.compress.utils import IOUtils as PythonIOUtils
        _pyCode = BytecodeLoader.makeCode(os.path.splitext(_launchedFile)[0], PythonIOUtils.toByteArray(_scriptStream), (_THIS_IS_ + _normalExtn))
        _scriptStream.close()
        exec(_pyCode)

```
and the file comes from `classLoader.getResourceAsStream(file)`

so something in this file is causing this error on PyString and clearly the deserialisation ID has changed. This is a pain. I need the compiled class to work in old and new versions of the master app.

Is there something I can do to avoid this issue? Or is there some way to determine why this file causes this issue, but other large ones don't?

As an alternative, is there any way to get `execfile(fileStream)` using a .py file to detect and use the .pyc file that's available - perhaps as another stream?

Or, can I load the pyc directly (instead of using a .class file) so that the byte code is dynamically created and thus I can avoid the pre-compile PyString issue.. This seems to work to load the .pyc file but I don't know how valid/safe it is?

```
        import marshal
        from org.python.apache.commons.compress.utils import IOUtils as PythonIOUtils
        _pycBytes = PythonIOUtils.toByteArray(_scriptStream)
        _scriptStream.close()
        _pyCode = marshal.loads("".join(chr(b & 0xFF) for b in _pycBytes[8:]))
        exec(_pyCode)
```
(yup - I had AI help with that last bit - but interesting that it seems to work).

I'm after the simplest, safest, most elegant solution, that hopefully avoids old/new jython version incompatibility issues.


Thanks in advance?

**Comment by Stewori** [comment]
Hey, I currently cannot work on this myself, but I can provide some guidance and assist in the fixing/merging/pull-request process in case you find a solution and want to apply it. Generally, the key method here is https://apidia.net/java/Jython/2.7.4/?pck=org.python.core&cls=.BytecodeLoader#fixPyBytecode-java.lang.Class-
Check out its source code, you will see how data from a pyc file can be used to create a `PyCode` object. This is a bit more complicated since the trick is not applied class-wise but possibly method-wise. If only one method is too large, only that method gets code from the pyc installed.
Is it possible that the class file bytecode version changed? We may have upgraded asm and we do not actively control the emitted bytecode version. If you rebuild the classfile using Jython 2.7.4, does it work then?

**Comment by yogi1967** [comment]
Yes. If I recompile with 2.7.4 to a class file then that loads ok but then I get the InvalidClassException when trying to load it on older jythons. So I need to fix a way to bypass this problem.

**Comment by Stewori** [comment]
Okay, after looking at the source of that method I realize that we are storing a `PyBytecode` object serialized via Java standard serialization to binary data, which then is stored via base64 in a String literal. (Don't judge me for that decision! At least it does not introduce new dependencies.)
So I guess it's a serialization issue (actually obvious from the error now that I think of it). Perhaps, setting an explicit serialization id for the PyBytecode class can fix it.

**Comment by yogi1967** [comment]
Perhaps. It’s odd that my other large class file does not trigger this issue?

Is 2.7.4 actually released yet, or could I get this fixed merged in?

**Comment by Stewori** [comment]
Looking at the error more closely, it actually complains about PyString. Probably, serialization of PyBytecode involves serialization of all sorts of objects, including PyString, - the data in the fields of a PyBytecode object. For some reason the jvm deems that one as incompatible. Maybe we actually made an incompatible change in PyString between Jython versions.
You are aware of how serialVersionUID works? IIRC Java assigns it automatically and changes it if the class changes in a possibly serialization-incompatible way. However, that heuristics is frequently false-positive in the sense that Java thinks something is incompatible although it would actually work. In such cases, one can assign a static field to a class `serialVersionUID = (some long literal)`, to indicate it should serialize anyway. So, maybe try fixing that number on PyString (to the value it tells you in the error).
It's explained here: https://apidia.net/java/OpenJDK/25/?pck=java.io&cls=.Serializable

**Comment by Stewori** [comment]
Yes, Jython 2.7.4 is already released, there is no way of changing it. There are these options:
- We fix this now for Jython 2.7.5 and you upgrade onwards to that. Release should be not too far away, not before Java 26 release though.
- You fix this in a custom build of Jython you can use internally.
- Perhaps it's possible to monkeypatch the `serialVersionUID`.

**Comment by Stewori** [comment]
For monkeypatching, see https://stackoverflow.com/questions/3301635/change-private-static-final-field-using-java-reflection
However, I guess this only allows changing an existing explicit serialVersionUID, not creating that field if it doesn't exist yet.
Then there is https://tersesystems.com/blog/2014/03/02/monkeypatching-java-classes/ but IDK if it (still) works.
In any case, you first have to verify if introducing a proper serialVersionUID field to PyString would actually solve it (in a custom Jython build).

**Comment by yogi1967** [comment]
Thanks. I’ll have a play. I wonder if we can use the ‘old’ id so that we get backwards compatibility.

**Comment by Stewori** [comment]
> I wonder if we can use the ‘old’ id so that we get backwards compatibility.

Yes, that's exactly what I meant. From the error it's not entirely clear which numer is the old one and which is the new one, but afterall it's only two numbers to try.

**Comment by Stewori** [comment]
I gave ChatGPT a shot on this issue and it pointed out some more workarounds. Sharing the advice here as-is, it's certainly an inspiration:

Yes — this is a classic Java serialization pain point. And you're correct: often the data is perfectly compatible, but the automatically generated `serialVersionUID` changed because the class structure changed slightly (method order, compiler version, etc.).

Short answer:
You **cannot tell the JVM to ignore serialVersionUID mismatch**, but you *can* work around it without recompiling the original library*. Here are your practical options, ordered from safest to most hacky.

---

# ✅ Recommended Solution: Custom ObjectInputStream (Override serialVersionUID Check)

You can override `ObjectInputStream.resolveClass()` to substitute the stream's `serialVersionUID` with the one from your current class at runtime.

Example:

```java
import java.io.*;

public class CompatibleObjectInputStream extends ObjectInputStream {

    public CompatibleObjectInputStream(InputStream in) throws IOException {
        super(in);
    }

    @Override
    protected ObjectStreamClass readClassDescriptor()
            throws IOException, ClassNotFoundException {

        ObjectStreamClass incoming = super.readClassDescriptor();
        ObjectStreamClass local = ObjectStreamClass.lookup(
                Class.forName(incoming.getName()));

        if (local != null) {
            if (incoming.getSerialVersionUID() != local.getSerialVersionUID()) {
                // Replace the descriptor to bypass serialVersionUID mismatch
                return local;
            }
        }

        return incoming;
    }
}
```

Then deserialize using:

```java
ObjectInputStream in =
    new CompatibleObjectInputStream(new FileInputStream("data.ser"));

MyObject obj = (MyObject) in.readObject();
```

### Why this works

Java checks serialVersionUID during `readClassDescriptor()`.
By replacing the incoming descriptor with the local one, you bypass the mismatch.

### When this is safe

Only do this if:

* Field structure is truly compatible
* No removed mandatory fields
* No type changes
* No changed field names

If fields differ, you'll get `InvalidClassException` or corrupted data.

---

# ⚠️ Option 2: Hex-edit the .ser file

Yes, this works — but it's fragile.

Inside the serialized stream, the serialVersionUID is stored as an 8-byte long after the class name. You could:

1. Extract the serialVersionUID from your current class:

   ```java
   ObjectStreamClass.lookup(MyClass.class).getSerialVersionUID();
   ```

2. Replace the 8-byte UID in the serialized file with this value.

But:

* You must handle endianness correctly (big-endian).
* Easy to corrupt the stream.
* Breaks if multiple classes in the stream.

Useful only as a one-off recovery tool.

---

# ⚠️ Option 3: Bytecode patch the class at runtime

You *could* use a Java Agent + ByteBuddy or ASM to redefine the class and inject the old serialVersionUID.

But this is far more complex than the custom ObjectInputStream approach and not worth it unless you’re building a framework.

---

# ❌ What You Cannot Do

* ❌ There is **no JVM flag** to ignore serialVersionUID mismatch.
* ❌ You cannot override it via system properties.
* ❌ You cannot “force” deserialize through normal API.

Java enforces this check strictly.

---

# 💡 Clean Long-Term Fix

If you control the codebase:

Add a fixed serialVersionUID to the class:

```java
private static final long serialVersionUID = 1L;
```

Then keep it stable across versions.

**Comment by Stewori** [comment]
That would still leave the question of how to get `CompatibleObjectInputStream` into `PyBytecode#parseSerializedCode`. You would have to write a modified `CompatiblePyBytecode` class and somehow get Jython to use that one for loading your code.

**Comment by Stewori** [comment]
AI's idea on this one:

Yes — you *can* patch this at runtime without modifying or redeploying the existing machinery.
But the approach depends on how invasive you're willing to be.

Since the machinery constructs `new ObjectInputStream(...)` internally, you can’t just substitute it normally. So your realistic runtime options are:

---

# ✅ Cleanest Runtime Fix: Java Agent (Bytecode Instrumentation)

You can attach a **Java Agent** that rewrites the bytecode of the problematic class at load time and replaces:

```java
new ObjectInputStream(...)
```

with:

```java
new CompatibleObjectInputStream(...)
```

This requires **no change to the original library JAR**.

### How it works

1. Write a Java agent.
2. Use ByteBuddy or ASM to intercept the constructor call.
3. Replace the instantiated class.

Example concept using ByteBuddy:

```java
public class SerializationAgent {
    public static void premain(String args, Instrumentation inst) {
        new AgentBuilder.Default()
            .type(ElementMatchers.named("com.example.MachineryClass"))
            .transform((builder, type, classLoader, module) ->
                builder.constructor(ElementMatchers.any())
                       .intercept(SuperMethodCall.INSTANCE))
            .installOn(inst);
    }
}
```

You’d specifically transform the method where `ObjectInputStream` is created.

Then run JVM with:

```
-javaagent:youragent.jar
```

Or even attach dynamically via Attach API (no restart required).

**Comment by yogi1967** [comment]
Thank you. Will digest.

**Comment by Stewori** [comment]
Hey, after sleeping over the issue, a perhaps more practicable solution occurred to me. Perhaps, it might be more feasible for you to write for the Jython 2.7.4 case a startup logic that converts the problematic class file(s) from 2.7.3 and writes them as *temporary*(?) files for Jython 2.7.4. You would have to manage the classpath or module path accordingly though.
The conversion itself might be doable based on https://pypi.org/project/javaobj-py3 for reading and using Jython 2.7.4's own facility for writing (since that's not supported by the lib). You would have to decode and encode the base64 data from the string literals of course, but that should be pretty standard. Just an idea.

**Comment by Stewori** [comment]
Actually, you won't need the javaobj-py3 lib at all. You can write the converter in Java based on Jython 2.7.4 and enable reading of the 2.7.3 class file via CompatibleObjectInputStream as suggested by the AI. So, for Jython 2.7.4 you could add a startup logic that e.g.

- copies the affected class files to a backup folder
- reads them via CompatibleObjectInputStream (more precisely, via code copied from PyBytecodeLoader but with ObjectInputStream replaced by CompatibleObjectInputStream)
- writes them again by the original code to the original place

Of course you can manage the tmp classes differently, you will know best. Idea is to rewrite them more or less on the fly by the described logic. Having this as a somewhat separate convertor allows to exchange the ObjectInputStream implementation.

**Comment by yogi1967** [comment]
Thank you. I’ll digest this and get AI looking into it 😉 

In the meantime, did you have any views on this method

```
import marshal
        from org.python.apache.commons.compress.utils import IOUtils as PythonIOUtils
        _pycBytes = PythonIOUtils.toByteArray(_scriptStream)
        _scriptStream.close()
        _pyCode = marshal.loads("".join(chr(b & 0xFF) for b in _pycBytes[8:]))
        exec(_pyCode)
```
It seems to work by loading the PYC file (ie not having a .class at all). Do you think this is valid/safe? Would this cause any runtime differences?

Thanks again.

**Comment by Stewori** [comment]
Sorry, I do not really understand that method and why it works (assuming the data is from a pyc file). At some point, a PyBytecode object should be created, but IDK whether marshal or exec does this bit of magic here. Perhaps exec recognizes the python bytecode and automatically creates the PyBytecode. I also do not remember right now how this works on class level, my usage of PyBytecode is on method-level (to target the overlong method issue narrowly). So, a runtime difference is probably be that the whole module is created as PyBytecode rather than only specific methods. This should have no notable effect if everything works as it should. Just internally, Python bytecode is used for the whole module, rather than Java bytecode. Since the latter gets jitted, it should be more performant than Python bytecode, but I doubt this would be measurable unless for very performance-heavy code. Whether it's valid: In theory, I guess so; in practice your tests must tell. I don't want to speculate about safety.
