### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not hierarchical when run as a jar-in-jar resource

### ISSUE THREAD

**Issue by Peng0529** [jython/jython#25]
log:
```
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(Unknown Source) ~[na:1.8.0_202]
	at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PrePy._getJarFileName(PrePy.java:362) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PrePy.getJarFileName(PrePy.java:345) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1195) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.initialize(PySystemState.java:1130) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.initialize(PySystemState.java:1085) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.initialize(PySystemState.java:1080) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.util.PythonInterpreter.initialize(PythonInterpreter.java:63) ~[jython-2.7.2.jar!/:2.7.2]
```
code:
```
        Properties props = new Properties();
        props.put("python.security.respectJavaAccessibility", "false"); 
        props.put("python.import.site","false");
        Properties preprops = System.getProperties();
        PythonInterpreter.initialize(preprops, props, new String[0]);
        PythonInterpreter interpreter = new PythonInterpreter();  //Here is the trigger point
        interpreter.exec("import math");
        interpreter.exec("import sys");
``
It works in IDE,But when I package it into a jar file and use it like this, I get an error: java -jar XXXX.jar.
I hope to get help, how do I use it

**Comment by ryanflegel** [comment]
I ran into this issue when trying to use Jython 2.7.2 in Spring Boot.

Here is the value of the URL when entering `getJarFileNameFromURL()` before it throws the exception:

`jar:file:/Users/ryan/code/boot/boot-service/build/libs/boot-service-2.0.2-SNAPSHOT.jar!/BOOT-INF/lib/jython-standalone-2.7.2.jar!/org/python/core/PrePy.class`

**Comment by wedoso** [comment]
I ran into the same issue as well when using Jython 2.72 with Spring Boot 1.3.6.

**Comment by mndzielski** [comment]
@wedoso 
I suggest you using 2.71, works fine with spring boot jar project

**Comment by wedoso** [comment]
> @wedoso
> I suggest you using 2.71, works fine with spring boot jar project

Do you mean Jython-standalone 2.7.1? I previously used Jython-slim 2.7.2. And I only see Jython-standalone was on 2.7.1

**Comment by mndzielski** [comment]
@wedoso 
Yeah I used standalone version, because I didn't need to install any packages. Well there is no rush to fix this issue unfortunately. 

If you need to install pip staff then use jython 2.7.0

**Comment by wedoso** [comment]
Thanks.. I just tried the standalone version with 2.7.1. But now I have below issue when initializing the interpreter.

        ImportError: Cannot import site module and its dependencies: No module named site.
        Determine if the following attributes are correct:
      * sys.path: [/Users/xxx/Documents/xxx/xxx-xxx/target/xxx-xxx.jar!/lib/Lib, __classpath__, __pyclasspath__/]

I was just using `this.pi = new org.python.util.PythonInterpreter();` to initialize the interpreter, I guess I need to specify the Jython location according to this [post](https://stackoverflow.com/questions/48215944/importerror-cannot-import-site-module-and-its-dependencies-no-module-named-sit)? But they were working on the different framework, so I don't know how to specify the Jython location in my Spring Boot.

**Comment by mndzielski** [comment]
```
    public static void main(String[] args) {

        Properties props = new Properties();
        props.put("python.console.encoding", "UTF-8");
        props.put("python.import.site", "false");
        Properties preProps = System.getProperties();
        PythonInterpreter.initialize(preProps, props, new String[0]);

        SpringApplication.run(WebApplication.class, args);
    }

```

Try this code, works for me with 2.7.1 version

**Comment by wedoso** [comment]
that resolves the issue. but can I use any python built-in packages with this standalone version? like `json`, `sys` or `math`? It seems I can't `import json` as I receive the error 
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named json
 
I could pass my unit test with IDE with `import json`, but get the above error after mvn packaging and running jar file.

**Comment by wedoso** [comment]
> that resolves the issue. but can I use any python built-in packages with this standalone version? like `json`, `sys` or `math`? It seems I can't `import json` as I receive the error
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named json
> ```
> 
> I could pass my unit test with IDE with `import json`, but get the above error after mvn packaging and running jar file.

update:
I tried to import different built-in modules. The ones I can successfully import include `sys` and `math`, rest of them are not including `json`, `random`, `datetime`, and `copy`

**Comment by wedoso** [comment]
After testing, without specifying system properties, the problem can be directly resolved by configuring `pom.xml` by adding this part in plugin if you are using Jython-standalone 2.7.2:

	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<configuration>
			<requiresUnpack>
				<dependency>
					<groupId>org.python</groupId>
					<artifactId>jython-standalone</artifactId>
				</dependency>
			</requiresUnpack>
		</configuration>
	</plugin>

Thanks for the post [here](https://stackoverflow.com/questions/34144715/jython-module-not-found-when-packaged-with-spring-boot/48468037).

Per discussion, the root cause is due to Jython jar is a nested jar while Spring Boot can't handle it without explicit configure the `pom.xml` as above.

**Comment by wedoso** [comment]
> After testing, without specifying system properties, the problem can be directly resolved by configuring `pom.xml` by adding this part in plugin if you are using Jython-standalone 2.7.2:
> 
> ```
> <plugin>
> 	<groupId>org.springframework.boot</groupId>
> 	<artifactId>spring-boot-maven-plugin</artifactId>
> 	<configuration>
> 		<requiresUnpack>
> 			<dependency>
> 				<groupId>org.python</groupId>
> 				<artifactId>jython-standalone</artifactId>
> 			</dependency>
> 		</requiresUnpack>
> 	</configuration>
> </plugin>
> ```
> 
> Thanks for the post [here](https://stackoverflow.com/questions/34144715/jython-module-not-found-when-packaged-with-spring-boot/48468037).
> 
> Per discussion, the root cause is due to Jython jar is a nested jar while Spring Boot can't handle it without explicit configure the `pom.xml` as above.

Update: I did the test for the Jython-slim 2.7.2, the above approach also work with Jython-slim 2.7.2

**Comment by 517863242** [comment]
That solves my problem perfectly. Thank you.
<requiresUnpack>
          <dependency>
                    <groupId>org.python</groupId>
                    <artifactId>jython-standalone</artifactId>
          </dependency>
</requiresUnpack>

**Comment by jeromerg** [comment]
@wedoso workaround works perfect. Thank you!

**Comment by K09Eel** [comment]
@wedoso Effective for Jython-standalone 2.7.3. Thanks!
