### ISSUE TITLE
MInecraft Plugin

### ISSUE THREAD

**Issue by BabyWaldi** [jython/jython#258]
Hello everyone
I want to start making Minecraft Python Plugins, but everytime I try to lunch, I get this error:

[16:49:17] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[16:49:20] [Server thread/WARN]: Legacy plugin PPLoader v1.0.0 does not specify an api-version.
[16:49:20] [Server thread/INFO]: [PPLoader] Loading PPLoader v1.0.0
[16:49:20] [Server thread/INFO]: [PPLoader] Loading Plugin hallowelt.py.dir
[16:49:23] [Server thread/WARN]: __main__:23: RuntimeWarning: PyTableCode.call caught a Throwable that is not an Exception:
[16:49:23] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
[16:49:23] [Server thread/WARN]: Jython internals might be in a bad state now that can cause deadlocks later on.
[16:49:23] [Server thread/WARN]: See http://bugs.jython.org/issue2536 for details.
[16:49:23] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: Traceback (most recent call last):
[16:49:23] [Server thread/WARN]:   File "<iostream>", line 23, in <module>
[16:49:23] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.getMethods(Class.java:2019)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaType.init(PyJavaType.java:467)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.createType(PyType.java:477)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.resolveType(PyType.java:352)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType.fromClass(PyType.java:2137)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType.fromClass(PyType.java:2115)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ClassicPyObjectAdapter$6.adapt(ClassicPyObjectAdapter.java:77)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ExtensiblePyObjectAdapter.adapt(ExtensiblePyObjectAdapter.java:44)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:131)
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.java2py(Py.java:2081)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaPackage.addClass(PyJavaPackage.java:87)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaPackage.__findattr_ex__(PyJavaPackage.java:139)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.__findattr__(PyObject.java:902)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.impAttr(PyObject.java:1035)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_next(imp.java:1163)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_logic(imp.java:1280)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_module_level(imp.java:1371)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.importName(imp.java:1544)
[16:49:23] [Server thread/WARN]:        at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.__call__(PyObject.java:433)
[16:49:23] [Server thread/WARN]:        at org.python.core.__builtin__.__import__(__builtin__.java:1232)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.importOneAs(imp.java:1580)
[16:49:23] [Server thread/WARN]:        at org.python.pycode._pyx0.f$0(<iostream>:75)
[16:49:23] [Server thread/WARN]:        at org.python.pycode._pyx0.call_function(<iostream>)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyTableCode.call(PyTableCode.java:173)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyCode.call(PyCode.java:18)
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.runCode(Py.java:1703)
[16:49:23] [Server thread/WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297)
[16:49:23] [Server thread/WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:292)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:211)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:118)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:92)
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonLoader.onLoad(PythonLoader.java:85)
[16:49:23] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:419)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:49:23] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.EbeanServer
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:49:23] [Server thread/WARN]:        ... 48 more
[16:49:23] [Server thread/WARN]: java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
[16:49:23] [Server thread/WARN]:
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:244)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:118)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:92)
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonLoader.onLoad(PythonLoader.java:85)
[16:49:23] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:419)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:49:23] [Server thread/WARN]: Caused by: Traceback (most recent call last):
[16:49:23] [Server thread/WARN]:   File "<iostream>", line 23, in <module>
[16:49:23] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.getMethods(Class.java:2019)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaType.init(PyJavaType.java:467)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.createType(PyType.java:477)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.resolveType(PyType.java:352)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType.fromClass(PyType.java:2137)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType.fromClass(PyType.java:2115)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ClassicPyObjectAdapter$6.adapt(ClassicPyObjectAdapter.java:77)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ExtensiblePyObjectAdapter.adapt(ExtensiblePyObjectAdapter.java:44)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:131)
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.java2py(Py.java:2081)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaPackage.addClass(PyJavaPackage.java:87)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaPackage.__findattr_ex__(PyJavaPackage.java:139)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.__findattr__(PyObject.java:902)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.impAttr(PyObject.java:1035)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_next(imp.java:1163)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_logic(imp.java:1280)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_module_level(imp.java:1371)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.importName(imp.java:1544)
[16:49:23] [Server thread/WARN]:        at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.__call__(PyObject.java:433)
[16:49:23] [Server thread/WARN]:        at org.python.core.__builtin__.__import__(__builtin__.java:1232)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.importOneAs(imp.java:1580)
[16:49:23] [Server thread/WARN]:        at org.python.pycode._pyx0.f$0(<iostream>:75)
[16:49:23] [Server thread/WARN]:        at org.python.pycode._pyx0.call_function(<iostream>)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyTableCode.call(PyTableCode.java:173)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyCode.call(PyCode.java:18)
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.runCode(Py.java:1703)
[16:49:23] [Server thread/WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297)
[16:49:23] [Server thread/WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:292)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:211)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:118)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:92)
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonLoader.onLoad(PythonLoader.java:85)
[16:49:23] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:419)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
[16:49:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:49:23] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.EbeanServer
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:49:23] [Server thread/WARN]:        ... 48 more
[16:49:23] [Server thread/WARN]: java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
[16:49:23] [Server thread/WARN]:
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.JavaError(Py.java:545)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyTableCode.call(PyTableCode.java:182)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyCode.call(PyCode.java:18)
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.runCode(Py.java:1703)
[16:49:23] [Server thread/WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297)
[16:49:23] [Server thread/WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:292)
[16:49:23] [Server thread/WARN]:        at org.cyberlis.pyloader.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:211)
[16:49:23] [Server thread/WARN]:        ... 9 more
[16:49:23] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.Class.getMethods(Class.java:2019)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaType.init(PyJavaType.java:467)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.createType(PyType.java:477)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry.resolveType(PyType.java:352)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType.fromClass(PyType.java:2137)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyType.fromClass(PyType.java:2115)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ClassicPyObjectAdapter$6.adapt(ClassicPyObjectAdapter.java:77)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ExtensiblePyObjectAdapter.adapt(ExtensiblePyObjectAdapter.java:44)
[16:49:23] [Server thread/WARN]:        at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:131)
[16:49:23] [Server thread/WARN]:        at org.python.core.Py.java2py(Py.java:2081)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaPackage.addClass(PyJavaPackage.java:87)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyJavaPackage.__findattr_ex__(PyJavaPackage.java:139)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.__findattr__(PyObject.java:902)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.impAttr(PyObject.java:1035)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_next(imp.java:1163)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_logic(imp.java:1280)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.import_module_level(imp.java:1371)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.importName(imp.java:1544)
[16:49:23] [Server thread/WARN]:        at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyObject.__call__(PyObject.java:433)
[16:49:23] [Server thread/WARN]:        at org.python.core.__builtin__.__import__(__builtin__.java:1232)
[16:49:23] [Server thread/WARN]:        at org.python.core.imp.importOneAs(imp.java:1580)
[16:49:23] [Server thread/WARN]:        at org.python.pycode._pyx0.f$0(<iostream>:75)
[16:49:23] [Server thread/WARN]:        at org.python.pycode._pyx0.call_function(<iostream>)
[16:49:23] [Server thread/WARN]:        at org.python.core.PyTableCode.call(PyTableCode.java:173)
[16:49:23] [Server thread/WARN]:        ... 14 more
[16:49:23] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.EbeanServer
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[16:49:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[16:49:23] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:49:23] [Server thread/WARN]:        ... 48 more

I use Jython standalone 2.7.3 and PPloader 1.1.0 for the Plugins, but its listed as 1.0.0 in the Server Log and for Minecraft I use spigot 1.18 on a Windows PC.

Can someone help me or know how to fix this?

**Comment by jeff5** [comment]
That's quite a stack dump, but the root cause appears to be that Jython can't find a class named in the `import` statement. Suspicion should therefore fall on the class loading path. The default class path is just that of the JVM.

Is it possible to create a simple example in which you simply try to import classes from the packages giving you trouble, and maybe work up in complexity from there? As you probably know, starting with something simple that works, then adding requirements like those of your application, until it breaks, is one way to pin down a problem in a complex application.

I have no knowledge of any of the other products you name. If class loading occurs other than by the default path, then Jython has features to support that, but it's not something I have used. In that case, I might first try a pure Java application (or plug-in) in the same environment to see if that can find the dependencies.

**Comment by BabyWaldi** [comment]
First thank you for the reply, but i solved the Problem. The Problem was, that PPloader (one of the Program that I use) was incopatible and I had downloaded the wrong Version. Now it works fine without any issues. So Jython wasn´t the Problem.

**Comment by jeff5** [comment]
Thanks for feeding back.
