### ISSUE TITLE
jython-standalone 2.7.3 urllib2 send request with request body occurs memoryview error

### ISSUE THREAD

**Issue by hung001** [jython/jython#287]
in jython-standalone, i use urllib2 to solve sending request things , and 2.7.2 works fine,but after i upgrade it to 2.7.3,it occurs error : 
TypeError: cannot make memory view because object does not have the buffer interface
using "urllib2.urlopen" to send request,the problem repears on local when the reqeuest send with request body, and it works when api don't need  request body.
so i think the request body may be the key of this problem,please check is it a bug or something?

**Comment by hung001** [comment]
*-- Edited for readability - Jeff*

code:
```
import urllib2
param["data"] = {"a": 1}
request = urllib2.Request(**param)
with closing(urllib2.urlopen(request, **url_param)) as response:
    code = response.code
    body = response.read()
```
error:
```
Traceback (most recent call last):
  File "<script>", line 59, in send_urllib_req
  File "<script>", line 59, in send_urllib_req
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 446, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\httplib.py", line 1082, in request
    self._send_request(method, url, body, headers)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\httplib.py", line 1122, in _send_request
    self.endheaders(body)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\httplib.py", line 898, in _send_output
    self.send(message_body)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\httplib.py", line 870, in send
    self.sock.sendall(data)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\_socket.py", line 1459, in meth
    return getattr(self._sock,name)(*args)
  File "D:\tools\maven\apache-maven-3.3.3\repo\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar\Lib\_socket.py", line 0, in sendall
TypeError: cannot make memory view because object does not have the buffer interface
```

**Comment by hung001** [comment]
it does change at Lib/_socket.py on 2.7.3, i see the diffrence that it uses "with memoryview(data)" directly,is it the reason?

**Comment by hung001** [comment]
ScriptEngine ENGINE =  new ScriptEngineManager().getEngineByName("python");
instead PythonInterpreter ，me use ScriptEngine

**Comment by jeff5** [comment]
> it does change at Lib/_socket.py on 2.7.3, i see the diffrenece that it uses "with memoryview(data)" directly,is it the reason?

Yes. The buffer was introduced to allow chunking, fixing an overflow, but the code assumes bytes (`str` or `array`). Some work (https://github.com/jython/jython/commit/c020c5e3cddc6fe13e9253afcec178f988e5c5e9) since 2.7.3 ensured that if the string is a `unicode` it gets implicitly encoded. If this is your case, it may work for you in 2.7.4 when we get that out.

I was a bit puzzled by `Lib_socket.py` in the traceback but quoting the code in fences put that right.

**Comment by jeff5** [comment]
The example code is not complete enough for me to reproduce the problem. The traceback is evidently from something else.

My guess is still that the object without a buffer interface is a `unicode` string and that we have dealt with the problem already. It's not possible to be certain on the evidence. Propose to close.

**Comment by hung001** [comment]
> > it does change at Lib/_socket.py on 2.7.3, i see the diffrenece that it uses "with memoryview(data)" directly,is it the reason?
> 
> Yes. The buffer was introduced to allow chunking, fixing an overflow, but the code assumes bytes (`str` or `array`). Some work ([c020c5e](https://github.com/jython/jython/commit/c020c5e3cddc6fe13e9253afcec178f988e5c5e9)) since 2.7.3 ensured that if the string is a `unicode` it gets implicitly encoded. If this is your case, it may work for you in 2.7.4 when we get that out.
> 
> I was a bit puzzled by `Lib_socket.py` in the traceback but quoting the code in fences put that right.

that's right.few months ago i solved it by transfer stuff like headers and request body to str,then I thought the reason was unicode things

**Comment by hung001** [comment]
thanks by the way

**Comment by tfmorris** [comment]
I can reproduce this with 2.7.3 and in our (OpenRefine's) case it was triggered by a unicode string. This version fails with the error above
```
import urllib2
url = "https://api-zbiory.mnk.pl/api/object/"+unicode("3173")
request = urllib2.Request(url, headers={'Accept-Language':'en'})
response = urllib2.urlopen(request) 
return response.read()
```
while this version works in 2.7.3 (ie the workaround is to wrap the offending unicode values with `str()`
```
import urllib2
url = "https://api-zbiory.mnk.pl/api/object/"+str(unicode("3173"))
request = urllib2.Request(url, headers={'Accept-Language':'en'})
response = urllib2.urlopen(request) 
return response.read()
```
