### ISSUE TITLE
Deadlocks in jython due to imports

### ISSUE THREAD

**Issue by Mo7mad-l3** [jython/jython#321]
Hello team.

We are encountering an issue in Jython 2.7.3 where it causes a deadlock due to static reference to the pySystemState.

We have a system that uses Jython in a multi-threaded manner, in some cases, the import process runs to import libraries such as codec, however, instead of using the pySystemState created for this thread, Jython is using another reference to the pySystemState to perform the import.

The issue is similar to https://bugs.jython.org/issue2536 and https://hg.python.org/jython/rev/2b06bc95594d, we've performed both suggested workaround of setting the XSS and updating the Jython Jar to 2.7.3 and the issue still occurs.

The method org.python.core.Py.getSystemState() is static and the method org.python.core.PySystemState.getCodecState() is synchronized.

The threads look like this, this thread is stuck in the getCodecState via pySystemState address 0x550e88b60, however, the pySystemState given to this thread is 0x54ed2e968

"https-openssl-nio-443-exec-245" - Thread t@1792157
   java.lang.Thread.State: WAITING
    at java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    - waiting to lock <57c8664e> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) owned by "Timer-46" t@1884806
    at java.base@11.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base@11.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
    at java.base@11.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
    at java.base@11.0.7/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
    at org.python.core.imp.load(imp.java:1016)
    at org.python.core.PySystemState.getCodecState(PySystemState.java:367)
    - locked <60eba516> (a org.python.core.PySystemState)
    at org.python.core.codecs.getDefaultEncoding(codecs.java:38)
    at org.python.core.codecs.decode(codecs.java:81)
    at org.python.core.PyString.decode(PyString.java:4035)
    at org.python.core.PyString.decode(PyString.java:4027)
    at org.python.core.PyUnicode.coerceForComparison(PyUnicode.java:1080)
    at org.python.core.PyUnicode.unicode___ne__(PyUnicode.java:800)
    at org.python.core.PyUnicode.__ne__(PyUnicode.java:794)
    at org.python.core.PyObject._ne(PyObject.java:1513)
    at org.python.pycode._pyx95.f$0(<string>:393)
    at org.python.pycode._pyx95.call_function(<string>)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.Py.runCode(Py.java:1703)
    at org.python.core.Py.exec(Py.java:1747)
    at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277) 

The other thread is below, in this thread, Jython is attempting to synchronize the pySystemState that was locked by the first thread.

"Timer-46" - Thread t@1884806
   java.lang.Thread.State: BLOCKED
    at org.python.core.JyAttribute.getAttr(JyAttribute.java:202)
    - waiting to lock <60eba516> (a org.python.core.PySystemState) owned by "https-openssl-nio-443-exec-245" t@1792157
    at org.python.core.PyObject.getJavaProxy(PyObject.java:376)
    at org.python.core.PyReflectedField._doget(PyReflectedField.java:29)
    at org.python.core.PyObject._doget(PyObject.java:1105)
    at org.python.core.PyObject.__get__(PyObject.java:3734)
    at org.python.core.PyObject.object___findattr__(PyObject.java:3766)
    at org.python.core.PyObject.__findattr_ex__(PyObject.java:925)
    at org.python.core.PySystemState.__findattr_ex__(PySystemState.java:407)
    at org.python.core.PyObject.__getattr__(PyObject.java:957)
    at warnings$py.f$0(warnings.py:424)
    at warnings$py.call_function(warnings.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.imp.createFromCode(imp.java:632)
    at org.python.core.util.importer.importer_load_module(importer.java:120)
    at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:175)
    at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
    at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:48)
    at org.python.core.imp.loadFromLoader(imp.java:821)
    at org.python.core.imp.find_module(imp.java:765)
    at org.python.core.imp.import_next(imp.java:1160)
    at org.python.core.imp.import_module_level(imp.java:1352)
    at org.python.core.imp.importName(imp.java:1544)
    at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
    at org.python.core.PyObject.__call__(PyObject.java:433)
    at org.python.core.__builtin__.__import__(__builtin__.java:1232)
    at org.python.core.imp.importOne(imp.java:1563)
    at ntpath$py.f$0(ntpath.py:533)
    at ntpath$py.call_function(ntpath.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.imp.createFromCode(imp.java:632)
    at org.python.core.util.importer.importer_load_module(importer.java:120)
    at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:175)
    at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
    at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:48)
    at org.python.core.imp.loadFromLoader(imp.java:821)
    at org.python.core.imp.find_module(imp.java:765)
    at org.python.core.imp.import_next(imp.java:1160)
    at org.python.core.imp.import_module_level(imp.java:1352)
    at org.python.core.imp.importName(imp.java:1544)
    at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
    at org.python.core.PyObject.__call__(PyObject.java:433)
    at org.python.core.__builtin__.__import__(__builtin__.java:1232)
    at org.python.core.imp.importOneAs(imp.java:1580)
    at os$py.f$0(os.py:726)
    at os$py.call_function(os.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.imp.createFromCode(imp.java:632)
    at org.python.core.util.importer.importer_load_module(importer.java:120)
    at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:175)
    at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
    at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:48)
    at org.python.core.imp.loadFromLoader(imp.java:821)
    at org.python.core.imp.find_module(imp.java:765)
    at org.python.core.imp.import_next(imp.java:1160)
    at org.python.core.imp.import_module_level(imp.java:1352)
    at org.python.core.imp.importName(imp.java:1544)
    at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
    at org.python.core.PyObject.__call__(PyObject.java:433)
    at org.python.core.__builtin__.__import__(__builtin__.java:1232)
    at org.python.core.imp.importOne(imp.java:1563)
    at linecache$py.f$0(linecache.py:68)
    at linecache$py.call_function(linecache.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.imp.createFromCode(imp.java:632)
    at org.python.core.util.importer.importer_load_module(importer.java:120)
    at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:175)
    at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
    at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:48)
    at org.python.core.imp.loadFromLoader(imp.java:821)
    at org.python.core.imp.find_module(imp.java:765)
    at org.python.core.imp.import_next(imp.java:1160)
    at org.python.core.imp.import_module_level(imp.java:1352)
    at org.python.core.imp.importName(imp.java:1544)
    at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
    at org.python.core.PyObject.__call__(PyObject.java:433)
    at org.python.core.__builtin__.__import__(__builtin__.java:1232)
    at org.python.core.imp.importOne(imp.java:1563)
    at traceback$py.f$0(traceback.py:314)
    at traceback$py.call_function(traceback.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.imp.createFromCode(imp.java:632)
    at org.python.core.util.importer.importer_load_module(importer.java:120)
    at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:175)
    at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
    at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:48)
    at org.python.core.imp.loadFromLoader(imp.java:821)
    at org.python.core.imp.find_module(imp.java:765)
    at org.python.core.imp.import_next(imp.java:1160)
    at org.python.core.imp.import_module_level(imp.java:1352)
    at org.python.core.imp.importName(imp.java:1544)
    at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
    at org.python.core.PyObject.__call__(PyObject.java:433)
    at org.python.core.__builtin__.__import__(__builtin__.java:1232)
    at org.python.core.imp.importOne(imp.java:1563)
    at org.python.pycode._pyx138371.f$0(<string>:1751)
    at org.python.pycode._pyx138371.call_function(<string>)
    at org.python.core.PyTableCode.call(PyTableCode.java:173)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.Py.runCode(Py.java:1703)
    at org.python.core.Py.exec(Py.java:1747)
    at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277)

**Comment by Stewori** [comment]
Do you  have reason to assume that the JVM recovers from a StackOverflowError or an OutOfMemory error as explained in  https://bugs.jython.org/issue2536 ? In that case, the initial issue must be avoided and analyzed. The JVM should not be recovered from errors, only from exceptions. If an error occurs one should only catch it for analysis and logging, not to keep the JVM running with further workload. Anyway, if no previous error recovery from  StackOverflowError or OutOfMemory has occurred, the issue might be different from bjo2536. Before any further analysis is attempted, that case needs to be decided, or risk is high to waste one's time.

In any case, it would be good if code for reproducing this issue could be shared.
Also, please try this with current master. There have been deadlock and race condition related fixes. An issue like this can be so complex and difficult to sort out that under all circumstances, any further investigation should take place using the master version only. One has to rule out the possibility that it might have already been fixed before investing work in this.

**Comment by Mo7mad-l3** [comment]
Hello Stefan.

Thank you for your reply,

We do not have any code to recover from an OOM or a stackOverflow.

The issue we are encountering is with the py.SystemState stores a static reference as a default system state that is used for the import.

Unfortunately, this issue is intermittent and I’ve tried to create multiple versions of a tester class to reproduce this issue, but was not able to reproduce it on demand.

The issue is occurring in our production environment, and in some deployments, it’s causing multiple daily restarts, some of which have hundreds of users.

The deadlock occurs when one thread uses the codec class and obtains the synchronization lock on the py.SystemState and another thread tries to use the py.System state to import another library, the deadlocked threads are listed in my original comment.

Kind regards.

**Comment by Stewori** [comment]
> We do not have any code to recover from an OOM or a stackOverflow.

Then this is not related to bjo2536.
A codec-related deadlock issue has been fixed in https://github.com/jython/jython/pull/243 but not yet released. As I already pointed out, you need to check if the issue can be reproduced on master. Next release is upcoming in Q2, but no date set.

**Comment by jeff5** [comment]
> A codec-related deadlock issue has been fixed in #243 but not yet released. As I already pointed out, you need to check if the issue can be reproduced on master. Next release is upcoming in Q2, but no date set.

Thanks for correlating this with that PR @Stewori . So we have reason to hope that 2.7.4 (of which I'm trying to build a beta right now) will address this.

**Comment by jeff5** [comment]
@Mo7mad-l3 : The [beta is up on Sonatype now](https://central.sonatype.com/artifact/org.python/jython-installer/2.7.4b1), so if you have the freedom to try that in your environment, we could learn whether this is still a problem or likely to be fixed already in 2.7.4.

**Comment by Mo7mad-l3** [comment]
Hello everyone, thank you for all the details, I checked the other bug, and the stack traces are still different, still working on a tester class that could reproduce the issue.

In the meantime, I'll see about using the beta in our test environment and see if we encounter any side effects..

Thank you all for all your efforts.

**Comment by Mo7mad-l3** [comment]
Hello team, I hope all is well, Any idea when 2.7.4 will be released?
 I see RC1 is released but the full release is not yet available.
Thanks in advance

**Comment by Stewori** [comment]
That depends on whether there come up issues with the RC. If no issues occur, the RC will be turned into a release after... what duration exactly? For 2.7.3 we had an RC phase of roughly 14 days. So I'd assume it will be more or less the same for 2.7.4.

**Comment by jeff5** [comment]
@Stewori I thought about the same. In fact, I added 19 August to the 2.7.4 milestone when rc1 came out.

rc1 took a few days longer than hoped, both the JAR updates and the tests locally. I can't guarantee it does anything for this issue.
