### ISSUE TITLE
_ast.astlist.__add__ leads to Java exception

### ISSUE THREAD

**Issue by lolive** [jython/jython#356]
I pip-installed chameleon with Jython 2.7.4.
The version chosen by pip was 3.10.2. 
I created this sample python file:

```
from chameleon import PageTemplate

template = PageTemplate("<div>Hello, ${name}.</div>")
result = template(name="John")
print(result)
```

But I get this error:

![image](https://github.com/user-attachments/assets/7b433cb5-2bfd-475f-a0a6-20d87d9d0d99)

Is it something I should report to the Chameleon team?
Or is it a bug related to Jython itself?

**Comment by lolive** [comment]
Fyi, compiler.py at line 1113 calls a function "template" with one single parameter "getname = econtext.get_name".

That function "template" looks like this:

![image](https://github.com/user-attachments/assets/f65f3352-48db-4f78-aeda-0146c78566bd)

**Comment by jeff5** [comment]
It's nice that still supports 2.7.x ... Fairly clearly, it is trying to write out of bounds into a list in the AST (index 0 in an array of size 0). The trace has gone through an "extend" method, so it looks like it knows it is might have to make the list bigger first, but I don't immediately see where that happens on the way to this:
https://github.com/jython/jython/blob/9b8a087042f413f11714e7df627e629c2599d1be/src/org/python/core/AstList.java#L474

On a quick look, I think I would blame us. A test in isolation would be to make an `_ast.astlist` and append. If that fails, we have no-one else to blame.

If you [post text](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) instead of images it makes it possible to quote the relevant bits.

**Comment by lolive** [comment]
Not sure I understood  which image you would have liked as text. 
Here is the log of my initial message, as a file. 
[chameleon.log](https://github.com/user-attachments/files/16840813/chameleon.log)

Does it help ?

**Comment by lolive** [comment]
_Edited by Jeff5 for formatting_
```
Traceback (most recent call last):
  File "test.chameleon.py", line 3, in <module>
    template = PageTemplate("<div>Hello, ${name}.</div>")
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/zpt/template.py", line 205, in __init__
    super(PageTemplate, self).__init__(body, **config)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py", line 137, in __init__
    self.write(body)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py", line 235, in write
    self.cook(body)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py", line 167, in cook
    program = self._cook(body, digest, names)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py", line 245, in _cook
    source = self._compile(body, builtins)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py", line 245, in _cook
    source = self._compile(body, builtins)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py", line 278, in _compile
    compiler = Compiler(
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 982, in __init__
    module.body += self.visit(node)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1029, in visit
    iterator = visitor(node)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1080, in visit_Module
    program = self.visit(node.program)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1029, in visit
    iterator = visitor(node)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1099, in visit_MacroProgram
    stmts = self.visit(macro)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1031, in visit
    for key, group in itertools.groupby(iterator, lambda node: node.__class__):
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1140, in visit_Macro
    nodes = itertools.chain(*tuple(map(self.visit, node.body)))
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1029, in visit
    iterator = visitor(node)
  File "/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py", line 1113, in visit_Context
    return template("getname = econtext.get_name") + \
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.set(ArrayList.java:448)
	at org.python.core.AstList.pyset(AstList.java:588)
	at org.python.core.AstList.setslicePySequence(AstList.java:486)
	at org.python.core.AstList.setslice(AstList.java:463)
	at org.python.core.AstList.astlist_extend(AstList.java:364)
	at org.python.core.AstList.extend(AstList.java:368)
	at org.python.core.AstList.astlist___add__(AstList.java:234)
	at org.python.core.AstList.__add__(AstList.java:224)
	at org.python.core.PyObject._basic_add(PyObject.java:2083)
	at org.python.core.PyObject._add(PyObject.java:2068)
	at chameleon.compiler$py.visit_Context$61(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1113)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.compiler$py.visit$54(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1037)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.__builtin__.map(__builtin__.java:772)
	at org.python.core.BuiltinFunctions.fancyCall(__builtin__.java:242)
	at org.python.core.BuiltinFunctions.__call__(__builtin__.java:161)
	at org.python.core.PyObject.__call__(PyObject.java:481)
	at chameleon.compiler$py.visit_Macro$62(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1186)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyGenerator.__iternext__(PyGenerator.java:161)
	at org.python.core.PyGenerator.__iternext__(PyGenerator.java:143)
	at org.python.modules.itertools.itertools$ItertoolsIterator.nextElement(itertools.java:61)
	at org.python.modules.itertools.groupby$1.__iternext__(groupby.java:71)
	at org.python.modules.itertools.groupby.__iternext__(groupby.java:114)
	at chameleon.compiler$py.visit$54(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1037)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.compiler$py.visit_MacroProgram$60(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1110)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.compiler$py.visit$54(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1037)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.compiler$py.visit_Module$59(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1090)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.compiler$py.visit$54(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1037)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.compiler$py.__init__$49(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py:1018)
	at chameleon.compiler$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/compiler.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:20)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:2408)
	at org.python.core.PyType.__call__(PyType.java:2389)
	at org.python.core.PyObject.__call__(PyObject.java:400)
	at chameleon.template$py._compile$17(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py:282)
	at chameleon.template$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:168)
	at org.python.core.PyFunction.__call__(PyFunction.java:437)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at chameleon.template$py._cook$15(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py:261)
	at chameleon.template$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:187)
	at org.python.core.PyFunction.__call__(PyFunction.java:449)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at chameleon.template$py.cook$9(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py:178)
	at chameleon.template$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.template$py.write$13(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py:235)
	at chameleon.template$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at chameleon.template$py.__init__$4(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py:142)
	at chameleon.template$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/template.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.PyObject._callextra(PyObject.java:589)
	at chameleon.zpt.template$py.__init__$2(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/zpt/template.py:205)
	at chameleon.zpt.template$py.call_function(/home/lolive/jython/2.7.4/Lib/site-packages/chameleon/zpt/template.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:20)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:2408)
	at org.python.core.PyType.__call__(PyType.java:2389)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx0.f$0(test.chameleon.py:5)
	at org.python.pycode._pyx0.call_function(test.chameleon.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1742)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297)
	at org.python.util.jython.runSimpleFile(jython.java:417)
	at org.python.util.jython.runStream(jython.java:449)
	at org.python.util.jython.runFile(jython.java:474)
	at org.python.util.jython.main(jython.java:678)
java.lang.IndexOutOfBoundsException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

**Comment by jeff5** [comment]
I think this bit tells us the problem is in Jython, not chameleon:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.set(ArrayList.java:448)
	at org.python.core.AstList.pyset(AstList.java:588)
	at org.python.core.AstList.setslicePySequence(AstList.java:486)
	at org.python.core.AstList.setslice(AstList.java:463)
	at org.python.core.AstList.astlist_extend(AstList.java:364)
	at org.python.core.AstList.extend(AstList.java:368)
	at org.python.core.AstList.astlist___add__(AstList.java:234)
	at org.python.core.AstList.__add__(AstList.java:224)
```
There's an add to a list, then somehow, in our code, we end up indexing an array out of bounds. But it's not like you'd indexed a Python list out of bounds, where you'd get a Python exception. Adding to an empty list is legitimate and the error you get here comes from Java.

- If the author had intended this list to be unmodifiable, or fixed in size, he would have given you a Python error message, not left it to Java to report.
- If he intended it to be extensible, there should somewhere be a bit of code that re-sizes the array, which I couldn't find and clearly didn't happen.

Obviously our `list` objects work properly and we test that extensively. This one is a special kind of list (not sure why). That's why I think this is our fault, and could be reproduced in isolation from chameleon with operations on a list got from an AST.

**Comment by jeff5** [comment]
In fact `append` works but `+` doesn't. Reproducer:
```
PS Jython-2> dist\bin\jython
Jython 2.7.5a1-DEV (heads/master:9b8a08704, Sep 7 2024, 18:20:37)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_271
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> tree = ast.parse("def f(): pass")
>>> tree.body
[FunctionDef]
>>> tree.body + ["hello"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.set(ArrayList.java:450)
        at org.python.core.AstList.pyset(AstList.java:588)
        at org.python.core.AstList.setslicePySequence(AstList.java:486)
        at org.python.core.AstList.setslice(AstList.java:463)
        at org.python.core.AstList.astlist_extend(AstList.java:364)
        at org.python.core.AstList.extend(AstList.java:368)
        at org.python.core.AstList.astlist___add__(AstList.java:234)
        at org.python.core.AstList.__add__(AstList.java:224)
        at org.python.core.PyObject._basic_add(PyObject.java:2083)
        at org.python.core.PyObject._add(PyObject.java:2068)
        at org.python.pycode._pyx4.f$0(<stdin>:1)
        at org.python.pycode._pyx4.call_function(<stdin>)
        at org.python.core.PyTableCode.call(PyTableCode.java:173)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1742)
        at org.python.core.Py.exec(Py.java:1786)
        at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277)
        at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:130)
        at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:115)
        at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:62)
        at org.python.util.InteractiveConsole.push(InteractiveConsole.java:188)
        at org.python.util.InteractiveConsole._interact(InteractiveConsole.java:169)
        at org.python.util.InteractiveConsole.interact(InteractiveConsole.java:127)
        at org.python.util.jython.runStream(jython.java:446)
        at org.python.util.jython.main(jython.java:700)
java.lang.IndexOutOfBoundsException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>>> tree.body.append("world")
>>> tree.body
[FunctionDef, world]
```

**Comment by lolive** [comment]
After checking the Chameleon code, the operator they use is +=
So the unit test for this Jython bug should test both the '+' operator *AND* the '+=' operator.

**Comment by jeff5** [comment]
Unfortunately, this is a can of worms. In CPython 2.7:
```
>>> import ast
>>> t = ast.parse('x = 1')
>>> type(t.body)
<type 'list'>
```
but in Jython 2.7:
```
>>> type(t.body)
<type '_ast.astlist'>
```
While our implementation of `list` behaves pretty well, `_ast.astlist` seems to be implemented without any thought that it might be modified in length. There is some good reason for this, since (in CPython, or Jython) nodes of the internal AST built by the parser are immutable during the parse. And what we see here is a list from the internal structure (from the `_ast` module).

CPython, however, deep-copies their value (a tree) to mutable Python objects when they are asked for via the `ast` module (no underscore), and when it needs to (e.g. to compile it) it will turn the external AST into the immutable internal form. There are families of functions called things like `ast2obj_stmt` and `obj2ast_stmt` for doing it.

This always seemed wasteful to me. In Jython we have an attempt to avoid doing it, by making all of the node classes full Python objects. Equivalents exist of the `ast2obj_*` and `obj2ast_*` functions, but they pretty much just do a cast, e.g. in [`StmtAdapter`](https://github.com/jython/jython/blob/master/src/org/python/antlr/adapter/StmtAdapter.java). But now we see a problem with that approach, although I don't see in that case why the sequence type can't simply be a `PyList`.

It looks like either a big change or a won't change.

(I've been thinking about the parser for Jython 3. Having tried to avoid it the duplication, I currently think the CPython approach, using immutable internal representation, is the less trouble.)

**Comment by jeff5** [comment]
I can fix the `__add__`, 
```
>>> t = ast.parse('x=1; global y; y=x*"hello"; x+=y.count("l")')
>>> t.body
[Assign, Global, Assign, AugAssign]
>>> p = [ast.Pass(), ast.Break()]
>>> t.body + p
[Assign, Global, Assign, AugAssign, Pass, Break]
>>> t.body
[Assign, Global, Assign, AugAssign]
>>> t.body += p
>>> t.body
[Assign, Global, Assign, AugAssign, Pass, Break]
```

But this `setslice` that it uses has multiple other problems, e.g.:
```
>>> t = ast.parse('x=1; global y; y=x*"hello"; x+=y.count("l")')
>>> t.body
[Assign, Global, Assign, AugAssign]
>>> p = [ast.Pass(), ast.Break()]
>>> t.body[1:1] = p
>>> t.body
[Assign, Pass, Break, AugAssign]
```
This shows that slice insertion is broken. The code is old and doesn't come with tests.

Standard tests on `list` are hard to apply because they instantiate the type under test, by calling the type, and `_ast.astList` is not instantiable: you only get them by parsing something. (Maybe a function can be substituted to parse an empty body.) I'm not currently proposing to fix the many bugs that we might find that way. Not under this issue, anyway.
