### ISSUE TITLE
Does jython support third-party libraries

### ISSUE THREAD

**Issue by myejb22** [jython/jython#48]
**In the project, jython-standalone is used to call the python script, 
and the third-party library time is called in the script:**
```tex
Exception in thread "main" Traceback (most recent call last):
  File "D:\project\submit_order.py", line 10, in <module>
    from appium import webdriver
  File "D:\install\python-3.6\Lib\site-packages\appium\webdriver\__init__.py", line 19, in <module>
    from .webdriver import WebDriver as Remote
SyntaxError: ("mismatched input ':' expecting RPAREN", ('D:\\install\\python-3.6\\Lib\\site-packages\\appium\\webdriver\\webdriver.py', 88, 23, 'def _make_w3c_caps(caps: Dict) -> Dict[str, List[Dict[str, Any]]]:\n'))
```

**Comment by jeff5** [comment]
Yes, but not if they're in Python 3 (for now).

**Comment by stuaxo** [comment]
That looks like it may be an error in the 3rd party driver, does it work in CPython on Windows?

It looks like it's getting confused by the : in the path after the drive letter.

**Comment by Stewori** [comment]
Indeed, it complains about a `:`. However, the colon after the drive letter should work fine. I think it's rather the colon in the type hint after `caps`, i.e. in `def _make_w3c_caps(caps: Dict) -> ...`
This is actually a syntax error in sense of parsing Python 3 using a Python 2 parser.

**Comment by myejb22** [comment]
> That looks like it may be an error in the 3rd party driver, does it work in CPython on Windows?
> 
> Yes it can be used

**Comment by myejb22** [comment]
> That looks like it may be an error in the 3rd party driver, does it work in CPython on Windows?
> 
> It looks like it's getting confused by the : in the path after the drive letter.


Yes it can be used

**Comment by stuaxo** [comment]
> Indeed, it complains about a `:`. However, the colon after the drive letter should work fine. I think it's rather the colon in the type hint after `caps`, i.e. in `def _make_w3c_caps(caps: Dict) -> ...`
> This is actually a syntax error in sense of parsing Python 3 using a Python 2 parser.

Good point, I was reading this on a phone so didn't see the whole message.

Are missing python 3 features being collected anywhere?

**Comment by Stewori** [comment]
Currently, Jython is 2.7 only. There is some ongoing work on Jython 3 but it's still early stage. See [the latest mail on this topic](https://sourceforge.net/p/jython/mailman/message/37063723/) for further info.

ATM the only viable way is to use an (older) Python 2.7 compliant version of the library if it exists. I don't think this needs to be specially tracked because it's really a basic syntax error. Jython 3 will presumably use the Python 3.8 grammar, so that shouldn't be an issue then. Of course, additional non-syntax issues are to be expected...

**Comment by stuaxo** [comment]
Thanks, very informative.

I tend to catch up with Jython every few years, it's good to see there is work being done :)
