### ISSUE TITLE
JavaWebStart compatibilty broken in 2.7.2

### ISSUE THREAD

**Issue by SchwingSK** [jython/jython#57]
The current implementation fails when instantiating a PythonInterpreter with the error:

> Exception in thread "main" java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421)
	at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427)
	at org.python.core.PrePy._getJarFileName(PrePy.java:362)
	at org.python.core.PrePy.getJarFileName(PrePy.java:345)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1195)
	at org.python.core.PySystemState.initialize(PySystemState.java:1130)
	at org.python.core.PySystemState.initialize(PySystemState.java:1085)
	at org.python.core.PySystemState.initialize(PySystemState.java:1080)
	at org.python.core.PySystemState.initialize(PySystemState.java:1075)
	at org.python.core.PySystemState.initialize(PySystemState.java:1070)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
	at org.python.core.Py.getThreadState(Py.java:1741)
	at org.python.core.Py.getThreadState(Py.java:1737)
	at org.python.core.Py.getSystemState(Py.java:1757)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)

This used to work in Jython 2.5.3

The reason is that when running Jython in JavaWebStart, the resources URLs when calling class.getResource(string) are of the form:

    jar:http://server:8080/signedWebApp/jython-slim-2.7.3a1.jar!/org/python/core/PrePy.class

This is not handled correctly by the current implementation.

**Comment by hansiang93** [comment]
The proposed PR looks good to me! but i believe i don't have the ability to approve the PR.

**Comment by jeff5** [comment]
I think I broke this in the refactoring the code, despite taking care. I don't use Web Start, so it is good the PR provides a test from someone who does.

@hansiang93 : thanks for taking a look at this. I'm assuming you went to the trouble of running this in the WebStart environment?

**Comment by hansiang93** [comment]
The organization i'm at ran into this same issue and i patched an internal jython build with this PR. It's been working great so far

**Comment by jeff5** [comment]
Even better. Let's get it in 2.7.3.

**Comment by jeff5** [comment]
Thanks to @SchwingSK for the patch and to @hansiang93 for the validation in ops.
