### ISSUE TITLE
fail to excute gradle publish 

### ISSUE THREAD

**Issue by xueneymar** [jython/jython#76]
Caused by: java.lang.ExceptionInInitializerError
        at org.python.core.imp.<clinit>(imp.java:42)
        at org.python.util.JycompileAntTask.getTo(JycompileAntTask.java:77)
        at org.python.util.GlobMatchingTask.scanDir(GlobMatchingTask.java:82)
        at org.python.util.GlobMatchingTask.execute(GlobMatchingTask.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        ... 99 more
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.PySystemState.<clinit>(PySystemState.java:70)
        ... 105 more

**Comment by jeff5** [comment]
Unfortunately, code in various dark corners of Jython still assumes characters are bytes. I've found most of the ones that *using* Jython leads you into. Building it less so.

In the context I would speculate that the problem is a non-ascii file path. (Don't forget home and temporary files.)

**Comment by xueneymar** [comment]
grateful ur reply! during use jpython I need some python's third modules support,so I download the source code and add third modules to (jython-master\lib-python\2.7\site-packages)  this dir,then excute gradle publish.

![image](https://user-images.githubusercontent.com/13958555/103720020-5ec59e00-5005-11eb-927c-51f663d2db80.png)
![image](https://user-images.githubusercontent.com/13958555/103720049-6d13ba00-5005-11eb-88ec-fa85b05a8195.png)

**Comment by jeff5** [comment]
If this works, you will have a jython-slim JAR that contains some extra (compiled) Python classes. This doesn't sound like a normal thing to do.

I think the normal thing to do would be one of:
1. Install Jython, or
2. Build a Java application with `jython-slim` as a dependency
and in either case then put your extra modules in `site` or on the `PYTHONPATH` where the application runs. (A wrapper script may be a good solution for that.)

You may still have your non-byte value problem, but in less confusing circumstances.

**Comment by caodeliu** [comment]
I also encountered this problem while using gradle.maybe you can compile the jar through the ant task.like this: ant -f build.xml -Djython.version=2.7.2 jar-standalone
