### ISSUE TITLE
Returned value is set to null when code contains multiple lines using ScriptEngine

### ISSUE THREAD

**Issue by hadim** [jython/jython#8]
Consider the following code : 

```java
package org.scijava.jupyterkernel.sandbox;

import javax.script.ScriptEngine;
import javax.script.ScriptException;
import org.scijava.Context;
import org.scijava.script.ScriptLanguage;
import org.scijava.script.ScriptService;

/**
 *
 * @author Hadrien Mary
 */
public class TestScriptEngine {

    public static void main(String[] args) throws ScriptException {
        // Only for testing purpose

        Context context = new Context();
        ScriptService scriptService = context.getService(ScriptService.class);
        ScriptLanguage scriptLanguage = scriptService.getLanguageByName("python");
        ScriptEngine engine = scriptLanguage.getScriptEngine();

        Object result = engine.eval("p=999\n555");
        System.out.println(result);

        scriptService = context.getService(ScriptService.class);
        scriptLanguage = scriptService.getLanguageByName("python");
        engine = scriptLanguage.getScriptEngine();
        
        result = engine.eval("555");
        System.out.println(result);

        context.dispose();
    }

}
```

It prints: 

```
null
555
```

While it should prints: 

```
555
555
```

**Comment by jeff5** [comment]
Python distinguishes `eval`, which expects only an expression, from `exec`, which executes a block. They actually use different grammars (different start points in the grammar). By convention, a block ends with a return, or the interpreter would run off down the memory.

In CPython 2.7.18, the different grammar is signalled by an argument, for `exec` we get:
```
>>> from dis import dis
>>> dis(compile("p=999\n555", "<script>", "exec"))
  1           0 LOAD_CONST               0 (999)
              3 STORE_NAME               0 (p)

  2           6 LOAD_CONST               1 (None)
              9 RETURN_VALUE        
```
and for `eval`:
```
>>> dis(compile("555", "<script>", "eval"))
  1           0 LOAD_CONST               0 (555)
              3 RETURN_VALUE        
```
It is an error to `eval` a block:
```
>>> dis(compile("p=999\n555", "<script>", "eval"))

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    dis(compile("p=999\n555", "<script>", "eval"))
  File "<script>", line 1
    p=999
     ^
SyntaxError: invalid syntax
```
It would be difficult and not really Python to do anything else.

The Java `ScriptEngine` makes no distinction between these two. It is initially a puzzle how we manage to trat them differently behind the single interface. In fact, we have to run the compiler to tell the difference: first we try an expression, then a block.

https://github.com/jython/jython/blob/15e6613ab8c7ac8a7b6de72a51bf32a2584f9397/src/org/python/core/ParserFacade.java#L111-L139
